### PR TITLE
Make activation scripts (test envs and releases) on supported machines

### PR DESCRIPTION
**Pull request by xylar**
This merge adds many features related 
* making activation scripts that 
  * activate the ``compass`` conda environment
  * loading modules
  * setting environment variables (`NETCDF`, `PIO`, etc.)
* Use E3SM compilers and MPI libraries on each machine to build:
  * ESMF (needed to make mapping files efficiently)
  * SCORPIO
* Documenting these chnages
* Updating the user's guide to make clearer that the instructions won't work yet (not until we have a 1.0.0 release).

As I added to the documentation, with these changes, a developer should now be able to run:
```
source ./load/load_compass_env.sh -m <machine> -c <compiler>
```
in the local compass branch to active the appropriate compass test environment as well as load the system modules and set the environment variables needed to build MPAS in standalone.  This always includes setting the environment variable to point to a SCORPIO build.

I have build SCORPIO on all machines with all compiler/MPI combinations I intend to support.  I have also build ESMF on all machines and compilers except Cori (no luck there so Cori will use the serial conda-forge version).

You no longer need the `-m <machine>` flag in `python -m compass setup` or `python -m compass suite`.  It knows what machine you are on because of the source command above.

When you set up a test case or suite, there will be a local link to the the environment activation script.  All you have to do there is:
```
source load_compass_env.sh
```
It already knows what machine and what compilers you asked for.

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman and @mattdturner, would you be willing to review this one?  You don't need to worry about the details in the `deploy` directory.  Those are for me to make the conda environments on each machine, build ESMF and SCORPIO, and make the activation scripts.  The main one is to try out the new suggested approach for activating the test environment for setting up, again:
```
source ./load/load_compass_env.sh -m <machine> -c <compiler>
```
and for running, again:
```
source load_compass_env.sh
```
in the test case or test suite directory.

**Comment by mark-petersen** [comment]
Could we make machine an optional argument, and by default read the machine with, in bash
```
HOST=`hostname -s`
if [[ $HOST = gr* ]] || [[ $HOST = ba* ]]; then
...
elif [[ $HOST = cori* ]]; then
```
Also, are the names identical to those listed by 
```
python -m compass list --machines
```
That would be useful to mention if the specified machine is not found.

**Comment by xylar** [comment]
@mark-petersen, those are good ideas.

I was hesitant to just identify the machine because we've had the problem in the past that the compute nodes don't have useful names.  But if it's optional, that would be okay.  Also, the machine is identified on the login node and the appropriate activation script is linked during setup, so there's no need to identify the machine a second time during run.

The machine names are the same ones from `compass list --machines`, yes.  The same config files are used so machines are so far only defined in one place.

By the way, I think this goes a long way toward also generating job scripts automatically for users but we're not there yet.

**Comment by xylar** [comment]
@matthewhoffman, this work obviously doesn't include any of the steps needed for linking in trilinos and whatever else you need for HO builds.  I would be keen to understand how to support that in a similar way but that's going to have to be beyond the scope of this PR.

**Comment by xylar** [comment]
@mark-petersen, I implemented both of your suggestions but I don't have time to test right now on all the machines so some bugs would not be surprising.

Everyone, please let me know how this goes.

**Comment by mattdturner** [comment]
@xylar When trying to test on Cori, I get the following error message when sourcing the `load_compass_env.sh` script
```
-bash: /global/cfs/cdirs/e3sm/software/compass/cori-haswell/test_compass1.0.0_intel_mpt.sh: Permission denied
```

It looks like `/global/cfs/cdirs/e3sm/software/compass` has the following permissions:
```
drwxrwx---   4 xylar    xylar    4.0K Apr 26 02:36 compass
```

Should the group be `e3sm` or should the permissions be changed to `drwxrwxr-x`?

**Comment by xylar** [comment]
Thanks @mattdturner.  The group should, indeed, have been `e3sm`.  I'll fix the script and rerun it to make sure it produces the right thing.

**Comment by xylar** [comment]
I see.  The problem is beyond the scope of the script.  I need to do those permissions manually.

**Comment by mark-petersen** [comment]
This looks great! I tested successfully on badger with simply 
```
source ./load/load_compass_env.sh
```
and could set up and run a nightly regression suite.

@xylar if I give a bad machine name, error message is not clean, but that might just be the bash calling a python script.
```
source ./load/load_compass_env.sh -m bug
Traceback (most recent call last):
  File "./load/get_activation_script.py", line 62, in <module>
    raise ValueError('machine {} doesn\'t have a config file in '
ValueError: machine bug doesn't have a config file in compass/machines.
sourcing:
-bash: source: filename argument required
source: usage: source filename [arguments]
```

**Comment by xylar** [comment]
@mark-petersen, I think I've fixed the error message.  Please try your `source ./load/load_compass_env.sh -m bug` again and let me know.

**Comment by xylar** [comment]
@mattdturner, I think permissions on Cori should be fixed now, but let me know if you still have trouble.

**Comment by mark-petersen** [comment]
Yes, that got rid of the bash error. Now I see this
```
source ./load/load_compass_env.sh -m bug
Traceback (most recent call last):
  File "./load/get_activation_script.py", line 62, in <module>
    raise ValueError('machine {} doesn\'t have a config file in '
ValueError: machine bug doesn't have a config file in compass/machines.
```
which is fine. I assume a `raise *Error` always produces a python traceback.

**Comment by mattdturner** [comment]
@xylar It looks like permissions are correct, but then there is an issue when running `python -m compass list`
```
[11:34]mturner@cori05  (deploy_with_system_esmf_scorpio):source load/load_compass_env.sh -c intel 
./load/get_activation_script.py:41: UserWarning: defaulting to cori-haswell.  Use -m cori-knl if you wish to run on KNL.
  warnings.warn('defaulting to cori-haswell.  Use -m cori-knl if you'
sourcing: /global/cfs/cdirs/e3sm/software/compass/cori-haswell/test_compass1.0.0_intel_mpt.sh
[11:34]mturner@cori05  (deploy_with_system_esmf_scorpio):python -m compass list
Traceback (most recent call last):
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/global/u1/m/mturner/MPAS/compass/compass/__init__.py", line 3, in <module>
    from compass.testcase import TestCase
  File "/global/u1/m/mturner/MPAS/compass/compass/testcase.py", line 4, in <module>
    from mpas_tools.logging import LoggingContext
ModuleNotFoundError: No module named 'mpas_tools'
```

**Comment by xylar** [comment]
>  I assume a raise *Error always produces a python traceback.

Yes, that's always the case.

**Comment by xylar** [comment]
@mattdturner, I'm looking into it.  But I'm also realizing that the problem with using a python script to activate a python environment is that the basic python that is on most machines is too old.  Hmm...

**Comment by xylar** [comment]
@mattdturner, I wasn't able to reproduce the problem so far.  Here's what I did:
```
$ source load/load_compass_env.sh  
Traceback (most recent call last):
  File "./load/get_activation_script.py", line 7, in <module>
    import configparser
ImportError: No module named configparser
```
But if I load some arbitrary environment with a newer python, I get the expected result:
```
$ source ~/miniconda3/etc/profile.d/conda.sh 
$ conda activate base
$ source load/load_compass_env.sh
./load/get_activation_script.py:41: UserWarning: defaulting to cori-haswell.  Use -m cori-knl if you wish to run on KNL.
  warnings.warn('defaulting to cori-haswell.  Use -m cori-knl if you'
sourcing: /global/cfs/cdirs/e3sm/software/compass/cori-haswell/test_compass1.0.0_intel_mpt.sh
craype-hugepages2M(43):ERROR:102: Tcl command execution failed: set             CRAYPE_DIR      $env(CRAYPE_DIR)

(test_compass_1.0.0) xylar@cori06:~/mpas_work/compass/deploy_with_system_esmf_scorpio> python -m compass list
Testcases:
   0: landice/dome/2000m/smoke_test
   1: landice/dome/2000m/decomposition_test
   2: landice/dome/2000m/restart_test
   3: landice/dome/variable_resolution/smoke_test

```

My guess is that something in your `.bashrc.ext` is messing things up.  Would you be willing to share what you've got there?

**Comment by mattdturner** [comment]
I had `source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_compass.sh` in my `.bashrc.ext` file.  I just commented out that line and opened a new terminal window.  Things now work as expected

**Comment by xylar** [comment]
Okay, yep, I would definitely not activate anything in your `.bashrc.ext`.  That has bad side effects like you're seeing.

**Comment by xylar** [comment]
I'm working on fixing the first issue (so the script can run with the default python 2.7).

**Comment by xylar** [comment]
@mattdturner, could you fetch and hard reset, and let me know if the fix I just pushed also works for you on cori?

**Comment by xylar** [comment]
Maybe check with a fresh terminal window (and make sure `which python` points to `/usr/bin/python`).

**Comment by mattdturner** [comment]
```
[13:09]mturner@cori10  (deploy_with_system_esmf_scorpio):git rev-parse HEAD
ac7b38b8c144e3a5a9affd3c3351161cbbb8a9ad
[13:09]mturner@cori10  (deploy_with_system_esmf_scorpio):which python
/usr/bin/python
[13:09]mturner@cori10  (deploy_with_system_esmf_scorpio):source load/load_compass_env.sh -c intel
./load/get_activation_script.py:49: UserWarning: defaulting to cori-haswell.  Use -m cori-knl if you wish to run on KNL.
  warnings.warn('defaulting to cori-haswell.  Use -m cori-knl if you'
sourcing: /global/cfs/cdirs/e3sm/software/compass/cori-haswell/test_compass1.0.0_intel_mpt.sh
[13:09]mturner@cori10  (deploy_with_system_esmf_scorpio):python -m compass list
Testcases:
   0: landice/dome/2000m/smoke_test
   1: landice/dome/2000m/decomposition_test
   2: landice/dome/2000m/restart_test
  <snip>
```

That works.

**Comment by xylar** [comment]
I tested on Anvil and it worked there, too.

**Comment by xylar** [comment]
Had to do a few fixes to get it working on Chrysalis.  I'm done for the day...

**Review by mattdturner — APPROVED** [review]
This works for me on Cori, and the activation scripts work on Compy (it fails to run with this issue https://github.com/MPAS-Dev/compass/issues/57).

**Comment by matthewhoffman** [comment]
@xylar , when I try on Grizzly without any arguments, I get the error below.  Also, how would one know what options there are for compiler on a given machine?

```
$ source ./load/load_compass_env.sh
sourcing: /usr/projects/climate/SHARED_CLIMATE/compass/grizzly/test_compass1.0.0_intel_impi.sh
failed: x
hdf5-parallel/1.8.16: /usr/projects/climate/SHARED_CLIMATE/software/grizzly/hdf5-parallel/1.8.16/intel-19.0.4/intel-mpi-2019.4: No such file or directory.

hdf5-parallel/1.8.16: HDF5-parallel is likely not built for this compiler and MPI combination.

Lmod has detected the following error:  /usr/projects/climate/SHARED_CLIMATE/modulefiles/all/hdf5-parallel/1.8.16: (hdf5-parallel/1.8.16):
While processing the following module(s):
    Module fullname       Module Filename
    ---------------       ---------------
    hdf5-parallel/1.8.16  /usr/projects/climate/SHARED_CLIMATE/modulefiles/all/hdf5-parallel/1.8.16

Lmod has detected the following error:  Cannot load module "pnetcdf/1.11.2". At least one of these module(s) must be loaded:
   hdf5-parallel

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    pnetcdf/1.11.2   /usr/projects/hpcsoft/modulefiles/toss3/grizzly/friendly-testing/pnetcdf/1.11.2

Lmod has detected the following error:  Cannot load module "netcdf-h5parallel/4.7.3". At least one of these module(s) must be loaded:
   hdf5-parallel

While processing the following module(s):
    Module fullname          Module Filename
    ---------------          ---------------
    netcdf-h5parallel/4.7.3  /usr/projects/hpcsoft/modulefiles/toss3/grizzly/friendly-testing/netcdf-h5parallel/4.7.3

/usr/bin/which: no pnetcdf-config in (/usr/projects/hpcsoft/toss3/common/x86_64/intel-clusterstudio/2019.4.070/impi/2019.4.243/intel/bin:/usr/projects/hpcsoft/toss3/common/x86_64/intel-clusterstudio/2019.4.070/impi/2019.4.243/intel64/bin:/usr/projects/hpcsoft/toss3/common/gcc/7.4.0/bin:/usr/projects/hpcsoft/toss3/common/x86_64/intel-clusterstudio/2019.4.070/compilers_and_libraries_2019/linux/bin/intel64:/usr/projects/hpcsoft/toss3/common/x86_64/cmake/3.16.2/bin:/usr/projects/climate/SHARED_CLIMATE/compass/grizzly/system/compass_1.0.0/intel/impi/esmf_8.1.1/bin:/usr/projects/climate/SHARED_CLIMATE/compass/grizzly/base/envs/test_compass_1.0.0/bin:/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/condabin:/users/mhoffman/software/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
```

**Comment by xylar** [comment]
@matthewhoffman, it looks like the `module` command is trying to use our custom-built modules, which can interfere with its ability to load IC's modules.   Do you perhaps have this in your `.bashrc`?
```
module use /usr/projects/climate/SHARED_CLIMATE/modulefiles/all
```
I had that in my `.bashrc` before and it caused me a large number of problems.  I eventually had to comment it out and instead include it in scripts only when absolutely necessary.

**Comment by xylar** [comment]
> Also, how would one know what options there are for compiler on a given machine?

Other than the documentation, I can't think of an obvious way to provide this information to the user.  I guess the activation script could have a `--list` flag that lists the available compilers and associated MPI flavors available?

**Comment by mattdturner** [comment]
It works for me on Grizzly, but I have 
```
module unuse /usr/projects/climate/SHARED_CLIMATE/modulefiles/all/
```

in a file that my `.bashrc` sources (I keep groups of modules in separate files so I can source them to switch environments)

**Comment by xylar** [comment]
@mattdturner, I don't think you should need:
```
module unuse /usr/projects/climate/SHARED_CLIMATE/modulefiles/all/
```
It shouldn't be included by default as far as I understand it.

**Comment by mattdturner** [comment]
@xylar it isn't included by default, but I have it included in some of the files that I source from time-to-time in order to change my environment.  So I include the `module unuse` in most of my environment files that I source, just in case I am switching from an environment that sources `/usr/projects/climate/SHARED_CLIMATE/modulefiles/all/` to one that doesn't.  If that makes sense

**Comment by xylar** [comment]
@mattdturner, Ah, I see.  That does make a lot of sense.  @matthewhoffman, would it make your life a lot easier if I put that line into the activation scripts? It would require making Grizzly and Badger kind of a special case but that's not the end of the world.

**Comment by xylar** [comment]
@matthewhoffman, following your inquiry, I added this:
```
$ source load/load_compass_env.sh --list
Available compilers and MPI libraries:
  -c intel -i impi
  -c gnu -i mvapich
  -c intel -i mvapich
```
I still need to add this to the documentation, but does that address your concern for now?

**Comment by matthewhoffman** [comment]
@xylar , thanks for addressing both my questions.  I would have been fine with referring to the documentation for compilers, but the script being able to tell a user is a nice touch.  I'm ok with the script requiring that your module settings are entirely clean - as long as we make a point of clearly stating that in the docs.

**Comment by xylar** [comment]
> as long as we make a point of clearly stating that in the docs.

Okay, I'll add that to the Grizzly and Badger developer's guide pages.  I don't think it applies on any other machines.

**Review by matthewhoffman — APPROVED** [review]

**Comment by xylar** [comment]
Thanks so much for the prompt and thorough reviews, @mattdturner and @matthewhoffman!

**Pull request merged**
