### PR TITLE
Add z-level ice-shelf 2d test cases

### PR DESCRIPTION
**Pull request by xylar**
The z-star versions of the test cases are now in a z-star subdir.

The z-level restart test has been added to the nightly suite.

The cavity thickness has been increased from 10 to 50 m to accommodate the z-level coordinate.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the `nightly` test suite without comparing with a baseline.  The changes to the ice-shelf 2d test group (both the ice draft and the directory structure) are such that they are expected to fail the comparison anyway.  Since no other tests were modified by the changes specific to this PR, I didn't feel like bit-for-bit checks were needed.

**Comment by xylar** [comment]
This will need to be rebased once #118 is merged.

**Comment by xylar** [comment]
@cbegeman, I think it would be sufficient for your review if you 1) make sure you can rerun all 4 `ice_shelf_2d` test cases (a chance to get to know the new compass a bit) and 2) take a look at the namelist files for the `z-level` setups to make sure they are consistent with testing you've done with this test case.

**Comment by xylar** [comment]
I ran with the `E3SM-Project` submodule but I also brought over the bug fixes from https://github.com/cbegeman/MPAS-Model/tree/ocean/minlevelcell_feature_bugfix in my branch https://github.com/xylar/E3SM/tree/ocn/bug-fixes-min-level-cell following the procedure described in https://github.com/E3SM-Project/E3SM/pull/4214#issuecomment-832007454

The bug fixes didn't seem t make a difference for these particular test cases (I didn't do a bit-for-bit check, thought), so I don't think it is necessary to wait for them to go into E3SM/master before merging this PR.

**Comment by cbegeman** [comment]
@xylar I successfully ran these test cases without my bugfixes. The namelist files look good. I didn't do any viz though. Did you bring over anything to serve the same function as https://github.com/MPAS-Dev/compass/blob/legacy/ocean/sub_ice_shelf_2D/plot_sub_ice_shelf_2D.py? If not, no problem. I'm fine with you merging this as-is. Thanks!

**Review by cbegeman — APPROVED** [review]

**Comment by xylar** [comment]
@cbegeman, bringing over that plotting script is a very good idea.  I'll add that.

**Comment by xylar** [comment]
I added a viz step to make those plots.  It's not like the old way where there's just a script you can hack up in the local directory.  You have to hack it up in the compass package.  But otherwise, it works similarly.

vert_grid
vert_grid (1)

**Comment by cbegeman** [comment]
Thanks, @xylar!

**Comment by xylar** [comment]
@cbegeman, thanks for the review!

**Pull request merged**
