### PR TITLE
Add flake8 to development environments

### PR DESCRIPTION
**Pull request by xylar**
This is helpful for folks that want to use it directly for linting or want to use the vim plugin.

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman, you can probably just approve by inspection.  I believe it *should* work to just rerun `./conda/configure_compass_env.sh` with the appropriate flags but I found I needed the `--recreate` flag in at least one case for it to notice new dependencies.  Let me know if that's the case for you.  It would be worth tracking down.

**Comment by xylar** [comment]
I'm just going to merge this...

**Comment by matthewhoffman** [comment]
@xylar , thanks for adding this so quickly.  I tried it out and it worked for me without the `--recreate` option.  It did require a bunch of new packages that seemed unrelated to flake8, but that might have been from other updates on master since I last ran the configure script.  Or it could just be the intricacies of conda package management, and I won't attempt to understand them!

**Comment by xylar** [comment]
That's really good to hear.  Yes, I wouldn't worry about other updates.  Most likely, you are right.  These just happen to be packages that have had updates in recent days, nothing to do with `flake8`. And definitely not worth investigating.  Just glad to know that you don't have to do `--recreate` to get updates.

**Pull request merged**
