### PR TITLE
Fix SOMA and ZISO script links

### PR DESCRIPTION
**Pull request by xylar**
There are two testcases that use links to `testing_and_setup/compass` using `mpas_model` as the base.  This was never the intended way of finding contents of testcases, and no longer works now that COMPASS is in its own repo.  These two links have been fixed in this merge.

partially addresses #20

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen, will this be easy for you to test?

**Comment by xylar** [comment]
## Testing

I didn't actually try to run these tests but the links are now correct:
```
xylar@burnham:~/data/mpas/test_soma_ziso/ocean/ziso/20km/default/forward$ ls -lah
...
lrwxrwxrwx 1 xylar xylar  105 Nov 10 15:05 make_particles.py -> /home/xylar/code/mpas-work/compass/fix_soma_ziso_links/ocean/scripts/LIGHTparticles/make_particle_file.py
```
and
```
xylar@burnham:~/data/mpas/test_soma_ziso/ocean/soma/32km/default/analysis$ ls -lah
...
lrwxrwxrwx 1 xylar xylar  101 Nov 10 15:05 check_particle_sampling.py -> /home/xylar/code/mpas-work/compass/fix_soma_ziso_links/ocean/soma/analysis/check_particle_sampling.py
```

**Review by mark-petersen — APPROVED** [review]
Ran nightly test suite, with compiled MPAS-O within the compass subdirectory. Worked great. thanks.

**Comment by xylar** [comment]
Thanks, @mark-petersen!

**Pull request merged**
