### PR TITLE
Print but don't raise errors in validation

### LINKED ISSUE #242: Error in baseline validation appears as test execution error
When validating a test against a baseline, if the validation fails because the baseline mesh has a different number of cells than the comparison run, the user sees and error in test execution rather than in baseline comparison.  This is confusing and should be fixed:
```
test execution:      ERROR
```

The traceback looks something like:
```
Exception raised in validate()
Traceback (most recent call last):
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/test_kdtree/compass/run.py", line 117, in run_suite
    test_case.validate()
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/test_kdtree/compass/ocean/tests/global_ocean/mesh/__init__.py", line 88, in validate
    compare_variables(test_case=self, variables=variables,
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/test_kdtree/compass/validate.py", line 137, in compare_variables
    result = _compare_variables(
  File "/gpfs/fs1/home/ac.xylar/mpas-work/compass/test_kdtree/compass/validate.py", line 231, in _compare_variables
    raise ValueError("Field sizes for variable {} don't match "
ValueError: Field sizes for variable xCell don't match files /lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20210923/pr_kdtree/ocean/global_ocean/SOwISC12to60/mesh/mesh/culled_mesh.nc and /lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20210923/pr_libnetcdf_481/ocean/global_ocean/SOwISC12to60/mesh/mesh/culled_mesh.nc.
```

### PR DESCRIPTION
**Pull request by xylar**
When errors occur during variable validation such as a mis-match in the number of cells, print an error and mark the test as failing but don't raise an exception.  This way, the errors will appear in the log and the test will be marked as failing but there will not be a stack trace, nor will the suite output show that the test execution (rather than baseline validation) failed.

closes #242

### CODE REVIEW

**Review by mark-petersen — APPROVED** [review]
This passes a general test. I did not test the behavior that causes errors, will trust @xylar's testing of that. Tested on grizzly with gnu, ran pr suite with comparison to previous run.

**Comment by xylar** [comment]
## Testing

To test this, I temporarily modified the QU240 mesh in this branch to have 200 km resolution instead.  I got the expected output in which the test case completes but the comparison with the baseline fails:
```
ocean/global_ocean/QU240/mesh
  * step: mesh
  test execution:      SUCCESS
  baseline comparison: FAIL
  see: case_outputs/ocean_global_ocean_QU240_mesh.log
ocean/global_ocean/QU240/PHC/init
  * step: initial_state
  test execution:      SUCCESS
  baseline comparison: FAIL
...
```

**Comment by xylar** [comment]
@mark-petersen, thanks for the review.

@matthewhoffman, if you are able to quickly review this by inspection, that would be wonderful.

**Review by matthewhoffman — APPROVED** [review]
Approved by inspection.  @xylar , thanks for showing the sample output of the behavior after these changes.

**Comment by xylar** [comment]
@matthewhoffman, thanks for the review.

**Pull request merged**
