### PR TITLE
Alphabetize suites when listing them

### PR DESCRIPTION
**Pull request by xylar**
It's annoying to have them in random order.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I verified that ``compass list --suites`` with this change produces the expected result:
```
  -c landice -t sia_integration
  -c ocean -t ec30to60
  -c ocean -t ecwisc30to60
  -c ocean -t nightly
  -c ocean -t qu240_for_e3sm
  -c ocean -t quwisc240
  -c ocean -t quwisc240_for_e3sm
  -c ocean -t sowisc12to60
```

Without this change, I am seeing:
```
$ compass list --suite
Suites:
  -c landice -t sia_integration
  -c ocean -t nightly
  -c ocean -t ecwisc30to60
  -c ocean -t quwisc240_for_e3sm
  -c ocean -t quwisc240
  -c ocean -t sowisc12to60
  -c ocean -t ec30to60
  -c ocean -t qu240_for_e3sm
```

**Comment by xylar** [comment]
@matthewhoffman, @mark-petersen and @vanroekel, this is a one-line change so I'm just going to merge it.  Just FYI.

**Comment by matthewhoffman** [comment]
Sounds good.  I assume the alphabetizing leaves the sublists of landice and ocean suites distinct.

**Comment by xylar** [comment]
Yes, cores are listed in the order they are added to `mpas_cores.py`.  Suites within a core are alphabetized.

**Pull request merged**
