### PR TITLE
FB-LTS Hurricane Test Case

### PR DESCRIPTION
**Pull request by jeremy-lilly**
This PR creates a version of the Hurricane Sandy test case from #618 for a new LTS scheme called FB-LTS -- see [E3SM-Project/E3SM#6224](https://github.com/E3SM-Project/E3SM/pull/6224).

Plots comparing the sea-surface height predicted by FB-LTS versus that predicted by LTS are given below.

**FB-LTS:**

**LTS:**

Checklist
* [x] User's Guide has been updated
* [x] Developer's Guide has been updated
* [ ] API documentation in the Developer's Guide (`api.rst`) has any new or modified class, method and/or functions listed
* [x] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [x] The `E3SM-Project` submodule has been updated with relevant E3SM changes
* [x] The `MALI-Dev` submodule has been updated with relevant MALI changes
* [ ] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes
* [x] New tests have been added to a test suite

### CODE REVIEW

**Comment by mark-petersen** [comment]
Testing on chicoma and perlmutter using:
```
./conda/configure_compass_env.py --conda /usr/projects/climate/mpeterse/miconda3 --compiler gnu
source load_dev_compass_1.2.0-alpha.9_chicoma-cpu_gnu_mpich.sh
compass list
...
 298: ocean/hurricane/DEQU120at30cr10rr2/mesh_fblts
 299: ocean/hurricane/DEQU120at30cr10rr2/init_fblts
 300: ocean/hurricane/DEQU120at30cr10rr2/sandy_fblts
 
 compass setup -p ~/repos/E3SM/lts-fb-jer-pr/components/mpas-ocean \
  -w $r/230311_ltsfb_test_DEQU120at30cr10rr2 \
  -n 298 299 300
```

**Comment by mark-petersen** [comment]
Using the E3SM PR https://github.com/E3SM-Project/E3SM/pull/6224 I was able to run this test case on both perlmutter and chicoma and produce the plots above. Thanks @jeremy-lilly for your great work!

**Comment by mark-petersen** [comment]
@jeremy-lilly could you check the user's guide here
https://mpas-dev.github.io/compass/latest/users_guide/ocean/test_groups/hurricane.html
which may be edited in this file:
https://github.com/MPAS-Dev/compass/blob/main/docs/users_guide/ocean/test_groups/hurricane.rst
and see if there is a place to add some description of the `fblts` option? Thanks.

**Comment by jeremy-lilly** [comment]
Thanks @mark-petersen! I've fixed the git history by removing that merge to `main`, committing a change to the docs, and the rebasing to `main`. Let me know if that doesn't look right!

**Review by mark-petersen — APPROVED** [review]
Thanks! The rebase and added notes to the doc page look good. I tested again with intel on chrysalis and gnu on perlmutter to be sure, and everything works!

**Comment by xylar** [comment]
@jeremy-lilly, the E3SM-Project submodule has finally been updated in https://github.com/MPAS-Dev/compass/pull/821 to bring in the changes you need.  Could you rebase (again) to include that?  Then, I'll run the tests and (hopefully) approve and merge.

**Comment by jeremy-lilly** [comment]
@xylar, I just rebased! Please let me know if anything doesn't look right. Thanks!

**Review by xylar — APPROVED** [review]
Tests are passing on Chrysalis (Intel/OpenMPI):
```
Test Runtimes:
06:22 PASS ocean_hurricane_DEQU120at30cr10rr2_mesh_fblts
46:58 PASS ocean_hurricane_DEQU120at30cr10rr2_init_fblts
06:21 PASS ocean_hurricane_DEQU120at30cr10rr2_sandy_fblts
Total runtime 59:43
PASS: All passed successfully!
```
and the documentation looks good.

**Comment by xylar** [comment]
@jeremy-lilly, thanks for the hard work and patience!

**Pull request merged**
