### PR TITLE
Update MALI-Dev submodule to latest develop

### PR DESCRIPTION
**Pull request by xylar**
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I was able to run the `full_integration` suite on Perlmutter with Gnu using #793

**Comment by xylar** [comment]
@matthewhoffman and @trhille, this seems like a good time to update the MALI-Dev submodule.  What do you think?

**Comment by xylar** [comment]
Assuming we want to test #793 on the latest MALI-Dev, this update will help me (and @andrewdnolan) do that.

**Review by matthewhoffman — APPROVED** [review]
I agree this is overdue.  Thanks, for setting it up and testing it, @xylar .

Trevor is on vacation this week, so I'll remove the review from him.

**Pull request merged**
