### PR TITLE
Fix nonhydro documentation

### PR DESCRIPTION
**Pull request by xylar**
This merge also includes a fix to the Chicoma docs

Checklist
* [x] User's Guide has been updated
* [x] Developer's Guide has been updated
* [x] API documentation in the Developer's Guide (`api.rst`) has any new or modified class, method and/or functions listed
* [x] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I built locally but am still seeing:
```
checking consistency... /home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.Nonhydro.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.SolitaryWave.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.SolitaryWave.configure.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.forward.Forward.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.forward.Forward.run.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.forward.Forward.setup.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.initial_state.InitialState.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.initial_state.InitialState.run.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.initial_state.InitialState.setup.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.visualize.Visualize.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.visualize.Visualize.run.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.solitary_wave.visualize.Visualize.setup.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.StratifiedSeiche.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.StratifiedSeiche.configure.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.forward.Forward.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.forward.Forward.run.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.forward.Forward.setup.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.initial_state.InitialState.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.initial_state.InitialState.run.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.initial_state.InitialState.setup.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.visualize.Visualize.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.visualize.Visualize.run.rst: WARNING: document isn't included in any toctree
/home/xylar/code/compass/fix_docs/docs/developers_guide/ocean/generated/compass.ocean.tests.nonhydro.stratified_seiche.visualize.Visualize.setup.rst: WARNING: document isn't included in any toctree
```
I don't yet understand why.

**Comment by xylar** [comment]
@cbegeman and @scalandr, I think we were all a bit exhausted in #374 and a few glitches in the documentation crept in at the end.  This is to fix those (because they're making it hard to have correct documentation in other PRs).

Please take a glance at my fixes and make sure there's nothing obviously wrong.  No need to build locally or anything.

Please approve today or tomorrow if you can because I want to rebase #525 onto this fix.

**Review by cbegeman — APPROVED** [review]
@xylar Thanks for this fix! Approving based on visual inspection.

**Comment by xylar** [comment]
Thank you @scalandr and @cbegeman for responding so promptly!  This is very helpful.

**Pull request merged**
