### PR TITLE
Switch to double output

### PR DESCRIPTION
**Pull request by xylar**
This merge adds  new streams template for double-precision output.  It makes other templates explicitly double precision and updates all `forward` and `ssh_adjustment` steps with new streams template.

For analysis steps steps, the streams files have been updated for double precision as well.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

So far, I have just set up all ocean test cases and ensured that `precision="single"` does not appear anywhere in the resulting setup.

**Comment by xylar** [comment]
@mark-petersen, do you have time to do some more thorough testing of this fix?

**Comment by xylar** [comment]
I'm assigning you to this.  Feel free to merge if you test this and it works correctly.

**Review by mark-petersen — APPROVED** [review]
@xylar thanks for the quick turn-around. I compared https://github.com/E3SM-Project/E3SM/commit/5fc4a7eae32a7dd7dd82b0d50e17ad0e53c8c3e4 to https://github.com/E3SM-Project/E3SM/pull/4518 using this compass branch, and it compared the `pr` test suite correctly (all pass with gnu opt.). I checked with grepping `streams.ocean` and some ncdump samples, and everything in output.nc files is written in doubles. Thanks!

**Pull request merged**
