### PR TITLE
Add a template for PRs with a checklist

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [ ] User's Guide has been updated
* [ ] Developer's Guide has been updated
* [ ] API documentation in the Developer's Guide (`api.rst`) has any new or modified class, method and/or functions listed
* [ ] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [ ] The `E3SM-Project` submodule has been updated with relevant E3SM changes
* [ ] The `MALI-Dev` submodule has been updated with relevant MALI changes
* [ ] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman and @trhille, could you have a look at this proposed checklist for all compass PRs and let me know what you'd like to add/change/remove?  If I understand right, as soon as this is merged, the checklist will appear as the starting point for the description of all subsequent PRs (under the commit text if you happen to make a single-commit PR).

**Comment by xylar** [comment]
@trhille, good point.  We use `pr` to make sure changes to compass don't break anything else but they're more relevant to testing E3SM than compass itself.

**Comment by xylar** [comment]
I can take that one out, and just put a generic check box for testing.

**Review by matthewhoffman — APPROVED** [review]
@xylar , I agree this is a welcome addition that should help with the integration process for both new developers and integrators.  

I'm approving as it, but one possible additional item would be if new tests have been added to a suite, as appropriate.

**Comment by xylar** [comment]
Good suggestion, @matthewhoffman.  Done!

**Comment by xylar** [comment]
Thanks for the reviews, @trhille and @matthewhoffman.

**Pull request merged**
