### PR TITLE
Update to compass 1.4.0-alpha.4, numpy >=2.0, mpas_tools 0.34.1, matplotlib >=3.9.0

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I successfully ran the `pr` and `full_integration` suites on Chrysalis (the former with Intel, the latter with Gnu).  I needed the fix from https://github.com/MPAS-Dev/MPAS-Tools/pull/574 so I will need to make a new MPAS-Tools release (0.34.1) with that fix.

**Comment by xylar** [comment]
@trhille and @sbrus89, I'm pinging you both for a quick review by inspection because I had to do some linting of code that I think you both might be the original authors of.  Could you take a quick look and make sure I didn't break anything that you can see just by visual inspection?  Feel free to run some tests if you like.  Make sure to `--recreate` the compass environment you use because of the new package constraints here.

**Review by trhille — APPROVED** [review]
@xylar, I'm approving by inspection of the landice tests. The changes there all look correct and innocuous, but I haven't tested. (By the way, @matthewhoffman was actually the one who wrote each of these landice cases.)

**Comment by xylar** [comment]
> By the way, @matthewhoffman was actually the one who wrote each of these landice cases.

Ah, good to know. GitHub recommended you as a reviewer so I just assumed you must be the author but that makes sense.

@matthewhoffman, feel free to have a look but I think @trhille took care of it.

**Comment by xylar** [comment]
@sbrus89, I'm going to hope for the best and merge this.  Without these changes, newly generated conda environments are broken.

I'm happy to help fix any problems that emerge with the `tides` test cases later on.

**Comment by matthewhoffman** [comment]
Looks good to me. Thanks, Xylar and Trevor for taking care of it.

**Pull request merged**
