### PR TITLE
Update namelist options for recent changes to Redi and Adams-Bashforth 2 

### PR DESCRIPTION
**Pull request by xylar**
This merge sets `config_Redi_min_layers_diag_terms = 0`, consistent with https://github.com/E3SM-Project/E3SM/pull/6077.

It also changes the time integrator from `split_explicit` to `split_explicit_ab2` nearly everywhere.

Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen and @cbegeman, I will test this to make sure all affected tests still work.

Once that's done, I'd appreciate your feedback to make sure we don't want to keep `split_explicit` (as opposed to `split_explicit_ab2`) for any tests.

**Comment by xylar** [comment]
## Testing

I ran the `pr` suite, the `gotm` test, the two `internal_waves` default tests, the `isomip_plus` z-star Ocean0 test, and the 4 `sphere_transport` tests on Chrysalis with Intel and OpenMPI.  I'll update when `sphere_transport` finishes but all other tests ran successfully.  I haven't looked at the output carefully or compared with baselines because the changes are expected to be larger than machine precision ("climate changing").

**Comment by cbegeman** [comment]
@mark-petersen Could you weigh in on whether this internal_wave test result is satisfactory? I wouldn't have expected there to be negative values.

AB2
image

split_explicit
image

**Comment by mark-petersen** [comment]
@xylar thanks for changing these tests. I agree that we should change to AB2 in all compass tests, since we made the switch in E3SM. 

@cbegeman thanks for noticing the negative relative RPE in the internal wave test case. Note that the vertical scale is a factor of 10 smaller, which means less spurious mixing over time. The negative values are concerning. It means that "anti-mixing" is going on, which would be gradient steepening or grid-scale noise. We should view some horizontal slices of temperature at those negative RPE points and compare the two time step schemes, to see what is going on. 

It might be that the timestep needs to be shortened a bit for AB2 relative to split explicit, because there are fewer iterations within each timestep, and we are seeing the result of a numerical instability.

**Comment by xylar** [comment]
@mark-petersen, I think we're still waiting for your response here.

**Comment by mark-petersen** [comment]
Sorry I missed this. I'm out for a week, so I think it would be better to remove the flag change from the `internal_wave` test case.

**Review by mark-petersen — APPROVED** [review]
Please merge after removing changes from `internal_wave` tests. The AB2 was tested at length for global simulations.

**Comment by xylar** [comment]
@cbegeman, I switched the internal waves test back to `split_explicit`.  Would you be in a good position to test it again?  If things work out, I think we can hopefully get this branch merged.

**Comment by xylar** [comment]
@cbegeman, sure that's fine.

**Comment by xylar** [comment]
Thanks for the earlier testing and review!

**Pull request merged**
