### PR TITLE
Remove legacy COMPASS

### PR DESCRIPTION
**Pull request by xylar**
This merge removes legacy COMPASS in anticipation of moving to the `compass` python package.

### CODE REVIEW

**Comment by xylar** [comment]
I create the `legacy` branch for continuing development of legacy COMPASS: https://github.com/MPAS-Dev/compass/tree/legacy

I will need to update the new documentation and README.md accordingly.  I will also need to update CI to work with the `legacy` branch.

**Comment by matthewhoffman** [comment]
@xylar , I never finished transitioning us to the new COMPASS repo, so I have no problems with making it legacy code when you are ready.  At this point I'll wait for the new system before switching over.

**Comment by xylar** [comment]
@matthewhoffman, sounds good.  I already made the `legacy` branch and have been using that for my own testing.  How about you @mark-petersen?  Could you try out the `legacy` branch and make sure it looks good to you?

**Comment by xylar** [comment]
@mark-petersen and @matthewhoffman, I'm going to merge this later today.  Let me know if you have any concerns.

**Review by matthewhoffman — APPROVED** [review]
I opened this webpage to reply this morning, but then forgot until now - go ahead!

**Review by mark-petersen — APPROVED** [review]
Yes, please proceed.

**Pull request merged**
