### PR TITLE
Constrain mamba to avoid recent issue

### PR DESCRIPTION
**Pull request by xylar**
See https://github.com/mamba-org/mamba/issues/1708

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I needed to delete my `~/miniconda3` but once I did that I was able to use `./conda/configure_compass_env.py` as usual to reinstall Miniconda3 just fine with this new constraint and then create the conda environment for compass.

So far, I don't have a great alternative for folks to try if they want to preserve their existing `miniconda3` environments.

**Comment by xylar** [comment]
@matthewhoffman, can you let me know if this works for you?  It may hang when it tries to install `mamba >=0.24.0`.  If so, I don't currently know of an alternative to deleting your `miniconda3` and starting over.  I would normally use `mamba` to investigate the problem but `mamba` *is* the problem.

**Comment by matthewhoffman** [comment]
@xylar , this works for me, and I didn't even need to delete my miniconda install first. Thanks for dealing with this.

**Comment by xylar** [comment]
Thanks @matthewhoffman!  Fingers crossed that this problem goes away permanently in the not-too-distant future.

**Pull request merged**
