### PR TITLE
LandIce: Added tests using the FO depth integrated model

### PR DESCRIPTION
**Pull request by mperego**
In this PR we add tests using the FO depth integrated model introduced in Albany PR https://github.com/sandialabs/Albany/pull/956.

In particular we added decomposition and restart tests for Thwaites and Humboldt glaciers.

We also updated tests' input files to comply with Albany PR https://github.com/sandialabs/Albany/pull/953, where options for integration rules changed. 
Removed the unused and outdated input file `albany_schoof_input.yaml`

Testing
* Checked that this PR does not modify results of existing tests.

Checklist
* [x] User's Guide has been updated
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes
* [x] New tests have been added to a test suite

### CODE REVIEW

**Comment by matthewhoffman** [comment]
## Testing

I ran the full_integration suite with this branch merged into #641 (required to get the version of Albany that includes MOLHO).  I compared the diagnostic velocity solution for the Thwaites decomp test between FO and MOLHO:

image

**Review by matthewhoffman — APPROVED** [review]
@mperego , thank you for adding these tests for the depth-integrated solver.  I will rebase and merge this once #641 is merged.

**Comment by xylar** [comment]
#641 is merged.

**Review by matthewhoffman — APPROVED** [review]
re-review after rebase (required)

**Comment by matthewhoffman** [comment]
(forgot to actually merge this after checks completed after rebase two weeks ago...)

**Pull request merged**
