### PR TITLE
Add optional support for `alphaBetaLab` package

### PR DESCRIPTION
**Pull request by xylar**
`alphaBetaLab` is needed to support WaveWatchIII mesh creation.  Since the original repo isn't in active development, we will use my fork for now.  This includes an improved list of dependencies and support for shapely 2.x, needed for compatibility with Compass.

`alphaBetaLab` will be installed from source since we cannot create a conda-forge package given that the original repo isn't in active development.

`alphaBetaLab` will only be installed if the `./conda/configure_compass_env.py` script is called with the `--with_alphabetalab` flag.

This feature will remain undocumented for now, but should be documented once WaveWatchIII mesh creation is added to Compass.

Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran:
```
./conda/configure_compass_env.py --env_name compass_test --recreate --verbose --with_alphabetalab
```
on my laptop and was able to successfully produce a conda environment that included `alphaBetaLab`.  Then, I was able to do:
```
cd alphaBetaLab/test
pytest testAb*.py
```
and all tests completed successfully.

**Comment by xylar** [comment]
@sbrus89, this is ready for you to test out, review, and use in your future development.

**Review by sbrus89 — APPROVED** [review]
I was able to create the conda environment with alphaBetaLab and run the tests on Perlmutter.

Thanks for including this @xylar!

**Comment by xylar** [comment]
Thanks @sbrus89.  Let's go ahead and get this in.

**Pull request merged**
