### PR TITLE
Remove critical passages from `landIceFracObserved`

### PR DESCRIPTION
**Pull request by xylar**
We need to do this before computing `landIceMask`.  Otherwise, critical passages cannot be used to open up channels of open ocean through areas covered by (grounded) land ice.

Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I tested this in conjunction with #807 and https://github.com/MPAS-Dev/geometric_features/pull/203.  I am (finally!) able to get the desired behavior close to the Carroll Inlet.

On the culled mesh, here is `landIceFracObserved`:
landIceFracObs

And here is `landIceMask`:
landIceMask


See #844 for details on how it looked without the critical passage.

**Comment by xylar** [comment]
@darincomeau, could you give this a quick look?  Do we finally have something an Stange that we can live with?

**Comment by darincomeau** [comment]
@xylar yes, that looks good!

**Review by darincomeau — APPROVED** [review]

**Comment by xylar** [comment]
Thanks @darincomeau!

**Comment by xylar** [comment]
What got missed here is also setting `landIcePressure` to zero in these critical passages.

**Pull request merged**
