### PR TITLE
Turn off surface restoring in global ocean

### PR DESCRIPTION
**Pull request by xylar**
We have discussed that we do not want to have surface restoring as part of dynamic adjustment anymore.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the `qu240_for_e3sm` suite on my laptop (Ubuntu, gnu) and it ran successfully.

I verified that `config_use_activeTracers_surface_restoring = .false.` in both steps of the `dynamic_adjustment` test case.

**Comment by xylar** [comment]
@vanroekel and @mark-petersen, since this is a one-line change, all I'm looking for in a review is your approval that we do, indeed, want to make this change.

**Review by vanroekel — APPROVED** [review]
confirming this is a change we want for MPAS spin ups

**Review by mark-petersen — APPROVED** [review]
Yes, this is fine, thanks.

**Comment by xylar** [comment]
Thanks @mark-petersen and @vanroekel!

**Pull request merged**
