### PR TITLE
Merge COMPASS contents from MPAS-Dev/MPAS-Model/landice/develop

### PR DESCRIPTION
**Pull request by xylar**
This merge brings in the full history of https://github.com/MPAS-Dev/MPAS-Model/tree/landice/develop/testing_and_setup/compass

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman, same deal as on #2: I'm just hoping of something of a sanity check from you. For example, that the first commits and last commits make sense and aren't missing anything. And that we're not changing files we don't want to be. Wouldn't hurt to run a test, but maybe not critical either.

**Comment by xylar** [comment]
@matthewhoffman, I'm confused about these supposed conflicts.  I don't think `landice/develop` should have modified any of these, right?  Maybe a local merge will work fine and GitHub is just confused?

**Comment by matthewhoffman** [comment]
@xylar , ok good to know.  I wasn't sure what to suggest. :)

**Comment by matthewhoffman** [comment]
@xylar , the PR page says 941 files have changed.  I'm assuming that's a symptom of the merge issue you mentioned.  Should I just be looking at this from the command line to do the sanity check?

**Comment by xylar** [comment]
@matthewhoffman, my assumption is that a lot of files have indeed changed since you last merged landice/develop to develop, but maybe not 941. 

I would suggest you do a test merge to master and make sure the landice directory looks identical to how it looks on MPAS-Model/landice/develop. And check that the commits on this branch (maybe just check the last 10 or so) make sense based on recent comments to MPAS-Model/landice/develop with compass changes.

**Review by matthewhoffman — APPROVED** [review]
@xylar , sorry this took me a month to look over.   A manual merge on the command line yielded expected results, and this looks good.

**Comment by matthewhoffman** [comment]
PS Let me know if you want me to merge this (or other) PRs in compass to share the burden.

**Comment by xylar** [comment]
@matthewhoffman, great!  Glad everything looks good.  I also recently did a test merge to make sure no new problems arose.  I'll take care of the merge, no problem.  Thanks for asking!

**Pull request merged**
