### PR TITLE
Reroute missing fluxes in data ice-shelf melt fluxes (DISMF)

### PR DESCRIPTION
**Pull request by xylar**
This merge adds the ability to reroute data melt fluxes remapped from the Adusumilli et al. (2020) dataset that were previously removed completely instead to the nearest sub-ice-shelf cell.

This requires first remapping to the base mesh, then rerouting, then culling land and masking land ice in the result.

In order to facilitate making DISMF datasets for existing meshes, the base mesh is also written out as part of `files_for_e3sm` and placed in `share/meshes/mpas/ocean`.

Checklist
* [x] User's Guide has been updated
* [x] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing on a new mesh

I successfully ran the IcoswISC `mesh` test and `init/remap_ice_shelf_melt` step.  The resulting melt fluxes are now fully accounted for:
```
Rerouting fluxes from 839 cells
Captured flux (kg/s):         20170179.4
Rerouted flux (kg/s):          7507101.3
Total flux (kg/s):            27677280.8
Total after rerouting (kg/s): 27677280.8
```

**Comment by xylar** [comment]
## Testing on an existing mesh

In the `files_for_e3sm` test case for an existing mesh, I tested the `ocean_mesh` and `remap_ice_shelf_melt` steps.  I needed to recreate the `IcoswISC30E3r5` base mesh, since I had deleted it.  I have copied this file to `share/meshes/mpas/ocean`.

The `remap_ice_shelf_melt` results are nearly the same as above:
```
Rerouting fluxes from 840 cells
Captured flux (kg/s):         20170108.3
Rerouted flux (kg/s):          7507172.4
Total flux (kg/s):            27677280.8
Total after rerouting (kg/s): 27677280.8
```

**Comment by xylar** [comment]
@darincomeau and @cbegeman, we should probably start a design document for the next generation of DISMF/DIB forcing.  This is my suggested first step in that direction -- making sure the total Adusumilli flux is the same as the total flux on the MPAS mesh.

**Comment by xylar** [comment]
For my test with a new IcoswISC30 mesh, here are the remapped Adusumilli fluxes on the base mesh:
dismf_base
And here are the fluxes on the culled mesh, including rerouting:
dismf_rerouted_culled

**Comment by xylar** [comment]
@cbegeman, thanks!  No, I don't think additional testing is needed for now.  I will try to figure out the area scaling that will keep the mass the same before and after remapping.  I'll ping you again once I've got that.

**Comment by xylar** [comment]
> . I will try to figure out the area scaling that will keep the mass the same before and after remapping. I'll ping you again once I've got that.

I have decided to fix that in #778, rather than here.

**Review by cbegeman — APPROVED** [review]
Approving based on existing testing, @xylar's reporting of the rerouted fluxes, and the fact that the remapped datasets agree in the magnitude of ice shelf fluxes (to within 12 decimal places between SORRM and RRSwISC6to18). Thanks for your work on this @xylar!

**Review by darincomeau — APPROVED** [review]
Approved based on existing testing.

**Comment by xylar** [comment]
@cbegeman and @darincomeau, thank you both for all the reviews!

**Pull request merged**
