### PR TITLE
Update mpas_tools to 0.31.0 and compass to 1.2.0-alpha.10

### PR DESCRIPTION
**Pull request by xylar**
The update MPAS-Tools package brings in some features needed for land-ice test cases as well as several bug fixes.  See https://github.com/MPAS-Dev/MPAS-Tools/releases.

Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
I will rebase and test the PR suite once #791 goes in.

**Comment by xylar** [comment]
@trhille and @matthewhoffman, sorry this took awhile.  This is a PR to bring in the newest MPAS-Tools release which I think has all the features you need.  I'll test on the ocean side to make sure things are either BFB or we understand why things changed.  Please make sure to set up a new conda environment (or recreate your existing one) and let me know if you're seeing the features you're hoping to make use of from `mpas_tools`.

**Comment by xylar** [comment]
## Testing

I ran the `pr` suite, comparing with a baseline from #791, on Chrysalis with Intel and OpenMPI.  

There appear to be small differences in the coastline in Icos240 mesh that are likely at the level of roundoff.  While I haven't been able to point to a specific cause, I don't see any cause for concern.  As a result of having a different number of cells, all the Icos240 tests fail the baseline check.  All other tests pass.

```
Test Runtimes:
00:06 PASS ocean_baroclinic_channel_10km_default
00:04 PASS ocean_baroclinic_channel_10km_threads_test
00:04 PASS ocean_baroclinic_channel_10km_decomp_test
00:04 PASS ocean_baroclinic_channel_10km_restart_test
00:02 PASS ocean_internal_wave_default
00:02 PASS ocean_internal_wave_vlr_default
03:15 PASS ocean_global_convergence_qu_cosine_bell
01:32 FAIL ocean_global_ocean_Icos240_mesh
00:42 FAIL ocean_global_ocean_Icos240_WOA23_init
00:30 FAIL ocean_global_ocean_Icos240_WOA23_performance_test
00:56 FAIL ocean_global_ocean_Icos240_WOA23_restart_test
00:56 FAIL ocean_global_ocean_Icos240_WOA23_decomp_test
00:56 FAIL ocean_global_ocean_Icos240_WOA23_threads_test
00:36 FAIL ocean_global_ocean_Icos240_WOA23_analysis_test
01:01 FAIL ocean_global_ocean_Icos240_WOA23_dynamic_adjustment
00:29 FAIL ocean_global_ocean_Icos240_WOA23_RK4_performance_test
00:58 FAIL ocean_global_ocean_Icos240_WOA23_RK4_restart_test
00:56 FAIL ocean_global_ocean_Icos240_WOA23_RK4_decomp_test
00:56 FAIL ocean_global_ocean_Icos240_WOA23_RK4_threads_test
00:00 PASS ocean_global_ocean_IcoswISC240_mesh
00:00 PASS ocean_global_ocean_IcoswISC240_WOA23_init
01:00 PASS ocean_global_ocean_IcoswISC240_WOA23_performance_test
00:00 PASS ocean_global_ocean_Icos_mesh
00:03 PASS ocean_global_ocean_Icos_WOA23_init
11:29 PASS ocean_global_ocean_Icos_WOA23_performance_test
00:00 PASS ocean_global_ocean_IcoswISC_mesh
00:06 PASS ocean_global_ocean_IcoswISC_WOA23_init
23:42 PASS ocean_global_ocean_IcoswISC_WOA23_performance_test
00:15 PASS ocean_ice_shelf_2d_5km_z-star_restart_test
00:14 PASS ocean_ice_shelf_2d_5km_z-level_restart_test
01:01 PASS ocean_isomip_plus_planar_2km_z-star_Ocean0
00:06 PASS ocean_ziso_20km_default
00:05 PASS ocean_ziso_20km_with_frazil
Total runtime 52:09
FAIL: 12 tests failed, see above.
```

**Comment by xylar** [comment]
@matthewhoffman and @trhille, it might be best to fold this into an update to v1.3.0-alpha.1 that also includes #788.  I may also want to do a new release of MPAS-Tools so https://github.com/MPAS-Dev/MPAS-Tools/pull/557 is available.

**Comment by matthewhoffman** [comment]
@xylar , combining those updates makes sense to me.

**Comment by xylar** [comment]
Closing this in favor of #793

**Pull request closed without merging**
