### PR TITLE
Fix location for mpas-seaice initial condition

### PR DESCRIPTION
**Pull request by xylar**
The files are placed in `...ice/mpas-seaice` whereas they were previously in `...ocn/mpas-seaice`.

### CODE REVIEW

**Comment by xylar** [comment]
The second commit here is just some clean-up to help with PEP8 and such.

**Comment by xylar** [comment]
@mark-petersen, I'll run a full QU240 test (through `files_for_e3sm`) and ping you to review once I post the results.

**Comment by xylar** [comment]
## Testing

I ran the QU240 mesh, init, performance test, dynamic adjustment and files-for-E3SM test cases, using the version of MPAS-Ocean from https://github.com/E3SM-Project/E3SM/pull/4750.

As expected, the resulting sea-ice initial condition is in:
```
assembled_files/inputdata/ice/mpas-seaice/QU240E2r1/mpassi.QU240E2r1.220124.nc
```
(It also contains `fCell` that is not all zeros.)

**Comment by xylar** [comment]
@mark-petersen, this is ready to review.  You can just review by inspection if you like.  The first commit is the important one, the second is clean up.

**Comment by xylar** [comment]
@mark-petersen, could you have a quick look at this when you have time?

**Review by mark-petersen — APPROVED** [review]
Yes, looks good. I've never seen an f-string, but I found it with a web search. That's handy!

**Comment by xylar** [comment]
Thanks, @mark-petersen!  Yeah, f-strings are almost always more readable and have been around since early python 3, so they're supported in all versions of python that folks *should* be using (currently python >=3.7).

@altheaden, deserves the credit for pushing me to use them.

**Pull request merged**
