### PR TITLE
Make sure ny is even in ISOMIP+ test cases

### PR DESCRIPTION
**Pull request by xylar**
This is needed to allow 4 km ISOMIP+ tests.

Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
@irenavankova, can you see if this fixes the issue you were seeing at 4 km?

**Comment by xylar** [comment]
## Testing

I was able to create a 4 km ISOMIP+ mesh and initial condition with this branch, where as @irenavankova saw the following error without these changes:
```
ocean/isomip_plus/planar/4km/z-star/Ocean0
compass calling: compass.ocean.tests.isomip_plus.isomip_plus_test.IsomipPlusTest.run()
  inherited from: compass.testcase.TestCase.run()
  in /lcrc/group/e3sm/ac.vankova/compass/code/test_sgr_V2/compass/testcase.py

compass calling: compass.run.serial._run_test()
  in /lcrc/group/e3sm/ac.vankova/compass/code/test_sgr_V2/compass/run/serial.py

Running steps: process_geom, planar_mesh, cull_mesh, initial_state, ssh_adjustment, performance
  * step: process_geom
  * step: planar_mesh
      Failed
Exception raised while running the steps of the test case
Traceback (most recent call last):
  File "/lcrc/group/e3sm/ac.vankova/compass/code/test_sgr_V2/compass/run/serial.py", line 320, in _log_and_run_test
    _run_test(test_case, available_resources)
  File "/lcrc/group/e3sm/ac.vankova/compass/code/test_sgr_V2/compass/run/serial.py", line 417, in _run_test
    _run_step(test_case, step, test_case.new_step_log_file,
  File "/lcrc/group/e3sm/ac.vankova/compass/code/test_sgr_V2/compass/run/serial.py", line 468, in _run_step
    step.run()
  File "/lcrc/group/e3sm/ac.vankova/compass/code/test_sgr_V2/compass/ocean/tests/isomip_plus/planar_mesh.py", line 55, in run
    ds_mesh = make_planar_hex_mesh(nx=nx + 2, ny=ny + 2, dc=dc,
  File "/lcrc/group/e3sm/ac.vankova/mambaforge/envs/test_sgr_V2/lib/python3.10/site-packages/mpas_tools/planar_hex.py", line 59, in make_planar_hex_mesh
    mesh = initial_setup(nx, ny, dc, nonperiodic_x, nonperiodic_y)
  File "/lcrc/group/e3sm/ac.vankova/mambaforge/envs/test_sgr_V2/lib/python3.10/site-packages/mpas_tools/planar_hex.py", line 88, in initial_setup
    raise ValueError('ny must be divisible by 2 for the grid\'s '
ValueError: ny must be divisible by 2 for the grid's periodicity to work properly.
```

**Comment by xylar** [comment]
I was also able to create 1 and 0.5 km meshes (just as a sanity check).

**Review by irenavankova — APPROVED** [review]
Yes, this fixes the 4 km problem for me.

**Review by irenavankova — APPROVED** [review]

**Comment by xylar** [comment]
Great, thank you @irenavankova!

**Pull request merged**
