### PR TITLE
Switch `pr` and `nightly` suites to use Icos meshes 

### PR DESCRIPTION
**Pull request by xylar**
We want to test meshes more similar to the E3SM v3 standard versions.

This merge also adds a set of tests on the IcoswISC240 mesh.

Cached files required for these suites are also added.

Checklist
* [x] User's Guide has been updated
* [x] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes
* [x] New tests have been added to a test suite

### CODE REVIEW

**Comment by xylar** [comment]
@cbegeman and @mark-petersen, are you willing to give this a look?  It's based off of #789 because I also needed that fix to be able to run the suites.

**Comment by xylar** [comment]
I still need to update documentation...

**Comment by xylar** [comment]
## Testing

I successfully ran the `pr` and `nightly` suites on Chrysalis with Intel and Open-MPI.  I didn't compare with a baseline because none is available for the Icos meshes.

**Comment by xylar** [comment]
@cbegeman and @mark-petersen, could you take a quick look at this?  I don't need you to run tests or look at the code changes in detail.  I just want to make sure you both agree that it's a good idea to switch the `pr` suite to use the Icos240, IcoswISC240, Icos (which defaults to Icos30) and IcoswISC (i.e. IcoswISC30) meshes instead of the QU and EC versions.

**Review by mark-petersen — APPROVED** [review]
Thanks @xylar! I agree with the change of meshes for the `pr` suite. 

This passed the nightly suite on chrysalis with intel and perlmutter with gnu using the head of E3SM master. 

My testing was as follows. Starting in the top directory of this compass branch:

chrysalis:
```
./conda/configure_compass_env.py --conda ~/miconda3 --compiler intel
source load_dev_compass_1.2.0-alpha.9_chrysalis_intel_openmpi.sh
compass suite -s -c ocean -t nightly  \
  -p ~/repos/E3SM/master/components/mpas-ocean \
  -w $n/ocean_model_240311_c8208a49_ch_ifort_openmp_master_compass_pr

srun -p debug -N 1 -t 1:00:00 --pty bash
cd $n/ocean_model_240311_c8208a49_ch_ifort_openmp_master_compass_pr
compass run
```

perlmutter:
```
./conda/configure_compass_env.py --conda ~/miconda3 --compiler gnu -m pm-cpu
source load_dev_compass_1.2.0-alpha.9_pm-cpu_gnu_mpich.sh
compass suite -s -c ocean -t nightly  \
  -p ~/repos/E3SM/master/components/mpas-ocean \
  -w $n/ocean_model_240311_c8208a49_lo_gnu-cray_openmp_master_compass_pr

# (downloaded a bunch of IcoswISC240 files)
salloc --nodes 1 --qos interactive --time 01:00:00 --constraint cpu --account=e3sm
cd $n/ocean_model_240311_c8208a49_lo_gnu-cray_openmp_master_compass_pr
compass run
```

**Review by cbegeman — APPROVED** [review]
@xylar These code changes all look good to me. Approving without testing based on successful tests from you and @mark-petersen. Thanks for getting this fix in!

**Pull request merged**
