### PR TITLE
Update MALI-Dev submodule

### PR DESCRIPTION
**Pull request by matthewhoffman**
This merge updates the MALI-Dev submodule in COMPASS after recently
merging E3SM-Project/master into MALI-Dev/develop.  It also includes a
number of other PRs over recent months.

### CODE REVIEW

**Comment by xylar** [comment]
As I said on Slack, what we've done for the `E3SM-Project` is to document either that the updated submodule is bit-for-bit with our test suite (`pr`) or which PRs from E3SM changed the results (hopefully in expected ways).  I wasn't as careful with the last update #275 because things got messy with an unexpected non-bit-for-bit PR that we plan to return to.

**Comment by trhille** [comment]
This passed all baseline comparison tests on Badger:

Test Runtimes:
00:14 PASS landice_dome_2000m_sia_restart_test
00:10 PASS landice_dome_2000m_sia_decomposition_test
00:14 PASS landice_dome_variable_resolution_sia_restart_test
00:08 PASS landice_dome_variable_resolution_sia_decomposition_test
03:32 PASS landice_enthalpy_benchmark_A
01:12 PASS landice_eismint2_decomposition_test
01:24 PASS landice_eismint2_enthalpy_decomposition_test
01:08 PASS landice_eismint2_restart_test
01:24 PASS landice_eismint2_enthalpy_restart_test
00:34 PASS landice_greenland_sia_restart_test
00:30 PASS landice_greenland_sia_decomposition_test
00:18 PASS landice_hydro_radial_restart_test
00:09 PASS landice_hydro_radial_decomposition_test
00:21 PASS landice_dome_2000m_fo_decomposition_test
00:27 PASS landice_dome_2000m_fo_restart_test
00:15 PASS landice_dome_variable_resolution_fo_decomposition_test
00:19 PASS landice_dome_variable_resolution_fo_restart_test
00:17 PASS landice_circular_shelf_decomposition_test
01:04 PASS landice_greenland_fo_decomposition_test
00:57 PASS landice_greenland_fo_restart_test
00:45 PASS landice_thwaites_decomposition_test
01:08 PASS landice_thwaites_restart_test
Total runtime 16:31
PASS: All passed successfully!

**Review by trhille — APPROVED** [review]
This looks good to me!

**Review by xylar — APPROVED** [review]
I'm approving based on @trhille's testing.

**Pull request merged**
