### PR TITLE
Update Quick Start for Developers

### PR DESCRIPTION
**Pull request by altheaden**
Quick Start needed info about config files and some misc typos fixed.

### CODE REVIEW

**Comment by altheaden** [comment]
@xylar, I wrote something up about config files, but I have no idea if the `:ref:` was set up correctly and I'm not sure how to check. Also, I'm not sure how everyone will feel about linking to the user's guide, so if you want it to link somewhere else (maybe `Command-line interface`?) I can do that.

**Comment by altheaden** [comment]
OK, thinking over this as I do more things. I was getting an error trying to set up the compass dev environment without a config file, but I'm realizing that's not something that I usually need to specify for it to work. It seems like this was more of an isolated incident than I realized initially, and saying `-f` is always required on an unknown machine is not true. Still think `-f` is worth mentioning in case a person gets the same error, but let me know your thoughts.

**Comment by xylar** [comment]
@altheaden, I think you're original idea was right. Any unknown machine will require a config file. So I think your changes are correct and appropriate as they are.

**Comment by altheaden** [comment]
@xylar, sounds good, just wanted to double check!

**Review by xylar — APPROVED** [review]
This looks great!  I built the docs locally and everything looks good.  Thanks for the work!

**Comment by xylar** [comment]
@altheaden, I believe that you don't have permission to merge the PR since you are in the "triage" group on GitHub.  On that assumption, I'm going to assign this to myself and merge.  Let me know if you see a green "Merge pull request" button on compass PRs.  If so, you have more permission than I thought.  If not, that's fine.  I'm happy to play "gatekeeper" to some extent.

**Comment by xylar** [comment]
You can delete the branch now if you want to keep things tidy.

**Pull request merged**
