### PR TITLE
Reorganize ISOMIP+ steps

### PR DESCRIPTION
**Pull request by xylar**
This merge reorganizes the ISOMIP+ test group to break the `initial_state` step into:
* `process_geom`: process the BISICLES topography data for the requested resolution
* `planar_mesh`: create a planar mesh of the requested resolution and size
* `cull_mesh`: cull out the grounded ice and land from the mesh
* `initial_state`: put the initial condition on the culled mesh

Some functionality has been taken out of the `geom` module and put into `process_geom` for simplicity. 

The `process_geom` step has been updated to use PEP8 conventions and to use `xarray` instead of `netcdf4`.  The code has been updated in other ways as well to shorten the code, increase code reuse and improve readability.

The remaining content in `geom` is shared between `cull_mesh` and `initial_state`, and has been cleaned up to comply with PEP8 (e.g. lowercase variables with underscores).

I also removed interface plotting (from the central section) on top of the overturning streamfunction, which we don't want because these interfaces don't apply.

Finally, I added a small fix to make sure horizontal plots of potential density and salinity respect the given `vmin` for the colormap.  It seems we need to set `clim` after any other alterations to the patches object or matplotlib will (seemingly at random) make `vmin` include 0.

This reorganization is in anticipation of supporting a `spherical_mesh` as an alternative to `planar_mesh`.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran all the `isomip_plus` test cases on Chrysalis with Intel and OpenMPI using the current E3SM `master` branch.  I used the compass `master` branch as a baseline and compared with this branch.  All tests were BFB.

**Comment by xylar** [comment]
@cbegeman, sorry to bombard you with PRs (especially over the weekend).  Please have a look and run any tests you would like to.  Please let me know if you have any concerns or suggestions.

**Comment by xylar** [comment]
My last commit didn't do what I expected so converting back to draft/in progress for now.

**Review by cbegeman — APPROVED** [review]
@xylar This looks great. It passes comparison with baseline with `ocean_isomip_plus_2km_z-star_Ocean0` and `ocean_isomip_plus_2km_sigma_thin_film_Ocean0` on cori with gnu-mpt.

**Comment by xylar** [comment]
Glad to hear that a test did work out somewhere!

**Comment by xylar** [comment]
@cbegeman, thanks so much for reviewing!

**Pull request merged**
