### PR TITLE
Update scorpio to 1.2.1

### PR DESCRIPTION
**Pull request by xylar**
Update to the latest SCORPIO (1.2.1).  This requires a new build of the `scorpio` conda package for Linux and OSX.

It also requires turning on timers because the build without timers fails.

Under Linux, linking in `libgomp` is required, presumably because of the timers.

Compiler, MPI and library module have been updated to match the current E3SM master (hash f019c5a53b)

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I will be building the new SCORPIO and running of the ocean nightly test suite with all supported compilers and MPI versions on these machines:

- [ ] Linux
  - [ ] mpich
  - [ ] openmpi
- [ ] OSX
  - [ ] mpich
  - [ ] openmpi
- [ ] Anvil
  - [ ] intel18
  - [ ] gnu
- [ ] Badger
  - [ ] intel
  - [ ] gnu
- [ ] Chrysalis
  - [ ] intel - impi
  - [ ] intel - openmpi
  - [ ] gnu
- [ ] Compy
  - [ ] intel
- [ ] Cori-Haswell
  - [ ] intel
  - [ ] gnu
- [ ] Cori-KNL
  - [ ] intel
  - [ ] gnu
- [ ] Grizzly
  - [ ] intel
  - [ ] gnu

**Comment by xylar** [comment]
This requires https://github.com/E3SM-Project/E3SM/pull/4362

**Comment by xylar** [comment]
OSX requires `-lc++` instead of `-lstdc++`.  A separate E3SM PR will be needed for this.

**Comment by xylar** [comment]
@cbegeman, @altheaden, @mark-petersen, @matthewhoffman and @vanroekel, this work to update to the latest version of SCORPIO, the same as used by E3SM, has been quite a bit of work involving a lot of testing on my part and 3 E3SM PRs.  I'm pretty confident that things are working.  But it would be really good to have a bit of testing by folks other than me.

You will almost certainly need to rebuild your development conda environment with:
```
./conda/configure_compass_env.py --recreate ...
```
Other than that, things should work the same as before.

I think it's really important that we try to stay in sync with the SCORPIO version used in E3SM as much as possible.  I'm hoping that will be easier in the future.

Let me know if you have any trouble.

**Comment by cbegeman** [comment]
@xylar I was able to run a compass test case on Chrysalis, gnu. Let me know if you want me to do more testing, including on other machines.

**Comment by xylar** [comment]
@cbegeman, that's great!  That's fine for now.  If you have a Mac and feel like testing there, that would be the other thing that would be most helpful.  But I know other folks have run into complications with proxy settings and whatnot so if you don't want to test on OSX, no worries at all.

**Comment by xylar** [comment]
@mark-petersen, @matthewhoffman and @vanroekel, are you able to review this PR?  If so, could you give me an estimate of when?  If not, could you remove yourself from the list of reviewers?  Thanks very much!

**Comment by vanroekel** [comment]
@xylar I'd be happy to test on any of the big machines if you felt that helpful.  I could do so today.  Just let me know what would be most helpful.  Sorry for letting this slip

**Comment by xylar** [comment]
@vanroekel, yes, please test on whichever machine you would be working with compass on anyway.  That would be very helpful.

**Comment by vanroekel** [comment]
Okay I'll check on my personal machine and chrysalis.  anvil appears down today so can't check there (at least I can't get an allocation)

**Review by vanroekel — APPROVED** [review]
tested nightly on chrysalis and baroclinic channel 10km test on my laptop and all worked smoothly!

**Comment by xylar** [comment]
@vanroekel, very glad to hear it.

**Comment by matthewhoffman** [comment]
@xylar , I removed myself.  My mac conda install is temperamental, and we're not currently using the conda-built libraries for MALI builds anyway (though we hope to eventually).

**Comment by xylar** [comment]
@mark-petersen, it seem you're not around so I'm going to take you off as a reviewer and proceed with this one.

**Pull request merged**
