### PR TITLE
Add `files_for_e3sm` step for remapping rms tidal velocity

### PR DESCRIPTION
**Pull request by xylar**
This field is needed for any meshes that will run in the `TMIX` configuration described here:
https://github.com/E3SM-Ocean-Discussion/E3SM/pull/76
The field gets remapped from a dataset that @irenavankova has preprocessed from the CATS tidal model,
see https://web.lcrc.anl.gov/public/e3sm/mpas_standalonedata/mpas-ocean/tidal_mixing/README.txt.

Checklist
* [x] Developer's Guide has been updated
* [x] API documentation in the Developer's Guide (`api.rst`) has any new or modified class, method and/or functions listed
* [x] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the `files_for_e3sm` test case (the one for pre-existing meshes) and pointed it to the `IcoswISC30E3r5` mesh.

I was able to generate the RMS tidal velocity:
xylar

My version differs only slightly from @irenavankova's:
irena

The places where they differ are where there is very little overlap between the original grid and the MPAS mesh:
mask
and results from a different approach to renormalization when there is less than 10% overlap between the meshes.

**Comment by xylar** [comment]
@irenavankova, this is ready for you to try out and review.

We should talk about the renormalization strategy.  What I chose to do was to renormalize if there is more than 1% overlap and to set the velocity to zero if there is less.

It seemed like you had a different approach to cells with less than 10% overlap where you always renormalized as if the overlap were 1%.  I think my approach is a little more standard and should lead to smoother results but I don't think it matters much because only a handful of cells are affected.

**Comment by xylar** [comment]
@irenavankova, I sent you an invitation to collaborate here.  If you accept, I can add you as a reviewer but you can still comment without being an official reviewer.

**Review by irenavankova — APPROVED** [review]
All works for me

**Comment by xylar** [comment]
@irenavankova, thanks for testing this out!

**Pull request merged**
