### PR TITLE
Minimum cmake for trilinos

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [ ] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
@trhille, this is the more permanent fix related to what I asked you to test in 
https://github.com/E3SM-Project/mache/pull/109#issuecomment-1450806601
Could you try this out and report back?  It will need to be tested in conjunction with:
```
--mache_fork xylar/mache --mache_branch  update_cmake_for_albany
```
as before.

**Comment by trhille** [comment]
@xylar, I'm an error when I run this:
```
./conda/configure_compass_env.py --conda ${CONDA_BASE} --mache_fork xylar/mache --mache_branch  update_cmake_for_albany --update_spack --spack /lustre/scratch4/turquoise/.mdt1/trhille/spack_test --tmpdir ${TMPDIR} --compiler gnu --mpi mpich --recreate --with_albany

...

recreating environment: dev_compass_1_2_0-alpha_4_gnu_mpich_albany
==> Error: /lustre/scratch4/turquoise/.mdt1/trhille/test_COMPASS_PR549/minimum_cmake_for_trilinos/conda/build_chicoma-cpu_gnu_mpich_albany/dev_compass_1_2_0-alpha_4_gnu_mpich_albany.yaml:14: CommentedMap([('cmake@3.23.0', None)]) is not valid under any of the given schemas
```

**Comment by xylar** [comment]
Okay, better leave this to me to debug.  This method is way too slow.

**Comment by xylar** [comment]
Thank you for being a good sport about a very tedious process.

**Comment by trhille** [comment]
No problem!

**Comment by xylar** [comment]
@trhille, these latest fixes are working for me on Chyrsalis. Could you give it another go?

**Comment by xylar** [comment]
It probably doesn't make sense to build new spack environments for all machines and configurations because of this change.  So far, there is still no change in compass dependencies that requires new spack environments.  So I suggest we make this an "in progress" PR until we need it.

**Comment by xylar** [comment]
AAAArgh!

I don't think that piece of the stack trace is very helpful.  I can give it a try myself...

**Comment by trhille** [comment]
😞

**Comment by xylar** [comment]
@trhille, it worked fine for me.  I deleted my `spack_test` and `spack_tmp` directories and started fresh.  Maybe that made a difference, not sure.

**Comment by trhille** [comment]
Okay, I can try that as well.

**Comment by trhille** [comment]
@xylar , okay I was able to run this successfully after removing my old spack_test and spack_temp directories! I'll set up and run `full_integration` now.

**Comment by xylar** [comment]
Thanks @trhille.  I ran into (and fixed) an issue I had with building the polaris environment on Chrysalis using the new environment without system cmake.  I don't yet understand why my compass test didn't reveal the same issue but maybe it was just luck in terms for what was already in the environment I was testing.

Anyway, it sounds like (assuming the `full_integration` testing goes well) we're done here until we have an actual need to build new spack environments.  Luckily, we're not there yet.

**Comment by trhille** [comment]
All `full_integration` test cases passed on Chicoma.

**Review by trhille — APPROVED** [review]
I don't know if it makes sense to approve a draft PR, but I'm doing so anyway!

**Comment by xylar** [comment]
I think this is a case where approving makes sense.  Thanks, @trhille!

**Comment by xylar** [comment]
Closing this because these changes are in #555

**Pull request closed without merging**
