### PR TITLE
Add additional flags to `pip install` command

### PR DESCRIPTION
**Pull request by altheaden**
In this PR I added a few flags to the `python -m pip install [-e] .` command. The flags are:
* `-vv` indicates very verbose output. This flag is used during the CI runs to help with debugging.
* `--no-deps` indicates that pip should not install runtime dependencies from PyPi.
* `--no-build-isolation` indicates that pip should not install build time dependencies from PyPi.

I also had to make several formatting changes to existing code in order to satisfy the linter.

Checklist
* [x] Developer's Guide has been updated
* [ ] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [ ] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
This looks good!  I feel like the changes are significant enough that I'd better do a quick test, though.

**Comment by altheaden** [comment]
Sounds good, if you would like me to test it instead (or in addition) I would be happy to do so as well.

**Comment by xylar** [comment]
## Testing

I ran:
```
./conda/configure_compass_env.py --conda ~/chrysalis/miniforge3/ --verbose --recreate --env_name compass_test
```
As expected, I saw the new `--no-deps` and `--no-build-isolation` flags where we want them.

Then, just to make sure `compass` was installed properly, I ran:
```
source load_compass_test_chrysalis_intel_openmpi.sh
compass list
```
and saw the expected list of packages.

**Review by xylar — APPROVED** [review]
@altheaden, excellent work as always.  Thanks for taking care of the nasty linting!

**Comment by xylar** [comment]
> if you would like me to test it instead (or in addition) I would be happy to do so as well.

I don't think that's necessary.  Just wanted to catch anything unexpected.

**Pull request merged**
