### PR TITLE
Update MALI-Dev submodule

### PR DESCRIPTION
**Pull request by matthewhoffman**
Update MALI-Dev submodule to ace160c641.  This is the final version used for ISMIP6-Antarctica 2300

Checklist
* [x] The `MALI-Dev` submodule has been updated with relevant MALI changes
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by matthewhoffman** [comment]
### Testing

`full_integration` suite passes with a few known failures.

**Comment by matthewhoffman** [comment]
@xylar , I tagged you to review because we haven't done one of these submodule updates very often.  Feel free to remove yourself or replace yourself with Trevor.

**Comment by xylar** [comment]
Happy to do it!

**Comment by xylar** [comment]
@matthewhoffman, which machine did you test on above?  I'll test on something different.

**Comment by xylar** [comment]
@matthewhoffman, I tried to test this on Chicoma but didn't quite manage before it went into DST.  I'm trying now on Compy.

**Comment by xylar** [comment]
@matthewhoffman, I'm seeing lots of failures on Compy.  They look something like:
```
CRITICAL ERROR: block_decomp_all_edges_in_block: Listed fewer edges than expected.
```
That sounds vaguely familiar but I haven't been able to find a previous mention of this error.

**Comment by xylar** [comment]
Aaaargh!  I'm giving up on Compy!  I went back to the old submodule and I get:
```
  225 |       call MPI_ALLREDUCE(localTmp, globalTmp, 1, MPI_DOUBLE_COMPLEX, &
      |                         1
......
 6407 |       call MPI_ALLREDUCE(localSum, globalSum, nFields, &
      |                         2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (COMPLEX(8)/INTEGER(8)).
make[3]: *** [mpas_global_s
```

**Comment by xylar** [comment]
I ran the `full_integration` test suite on Chrysalis with this branch.  All tests were successful except:
```
landice/humboldt/mesh-3km_restart_test/velo-fo_calving-von_mises_stress_damage-threshold_faceMelting
```
as we have noted.  I made an issue for this on MALI-Dev: https://github.com/MALI-Dev/E3SM/issues/60.

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
@matthewhoffman, please merge when you're ready.

**Pull request merged**
