### PR TITLE
Add E3SM-Project and MALI-Dev submodules

### PR DESCRIPTION
**Pull request by xylar**
Remove `MPAS-Model` submodules.

Change references to `MPAS-Model` repo --> `E3SM-Project` and `MALI-Dev` both the code and the documentation.

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen and @matthewhoffman, could you test and review this a your convenience?

**Comment by matthewhoffman** [comment]
@xylar , this looks good and I haven't encountered any problems in testing.  However, one issue I quickly realized is that our day-to-day testing will not be using the `E3SM-Project/E3SM` repo but instead in the `MALI-Dev/E3SM` repo.  I'm on the fence about suggesting we add a 2nd submodule for MALI or if the MALI team just manually adds the appropriate remote and branch before running any tests.  That touches a larger question of how frequently the ocean team anticipates updating the submodule.  Would that always be master?  Would a shared submodule hash ever be what we want in this situation, even if MALI was developing out of `E3SM-Project/E3SM`?

**Comment by xylar** [comment]
I think it's quite important to have some way to indicate which E3SM git hash(es) a given compass is compatible with.  So it does seem like we need a `MALI-Dev/E3SM` submodule, suggesting that we need to use `E3SM-Project/E3SM` for the other, rather than just `E3SM`.

**Comment by matthewhoffman** [comment]
That makes sense.  What about calling them `MPAS-Ocean` and `MALI` instead of `E3SM-Project/E3SM` and `MALI-Dev/E3SM`?  Or `E3SM-MPASO` and `E3SM-MALI`.

**Comment by xylar** [comment]
If the submodules don't have a clear connection to the org/repo, I would go for `MPAS-Ocean` and `MALI` without the `E3SM`, which doesn't add clarity in my view.  @mark-petersen, what do you think?

**Comment by xylar** [comment]
@matthewhoffman, I'm trying out `MPAS-Ocean` and `MALI` submodules and a couple of points for further discussion are emerging.
* It isn't clear to me that it's a good idea to have a submodule `MPAS-Ocean` that points to `E3SM-Project/E3SM`.  The long-term goal is for this submodule to point to the version of E3SM that is compatible with all compass cores (ocean, landice and eventually omega).
* But if this submodule is named `E3SM`, it isn't very clear that `landice` developers shouldn't be using that submodule and should use `MALI` instead, particularly since there's a `components/mpas-albany-landice` in there.
* It's weird documenting the path `MPAS-Ocean/components/mpas-ocean` and `MALI/components/mpas-albany-landice` in a bunch of places, but maybe that's unavoidable.

Anyway, I wanted to raise these questions/concerns now before I get too far with modifying the documentation (again).

**Comment by matthewhoffman** [comment]
@xylar , I agree the situation is awkward.  The confusing meaning of the submodules is what motivated me to suggest `E3SM-MPASO` and `E3SM-MALI`, as in 'it is E3SM and for MPASO'.  (Could also do `E3SM-for-MPASO` I suppose.)  While the long term goal is a single submodule, I don't MALI being included for a year or two.  One other option would be have the ocean use `E3SM-Project/E3SM` (or just plain `E3SM` and MALI use `MALI-Dev/E3SM`.

**Comment by xylar** [comment]
I think at this point I would, indeed, lean toward `E3SM-Project/E3SM` and `MALI-Dev/E3SM`.  That way, nothing is getting hidden under the rug and there's no implication about which component "owns" `E3SM-Project/E3SM`.  It would also be straightforward to add `E3SM-Ocean-Discussion/E3SM` as another submodule if that seems useful (I started to do that but realized it's potentially counterproductive and confusing because we *don't* plan to keep it in sync with compass and we don't want users treating it as the default place to run from or anything).

@mark-petersen, any thoughts?

**Comment by matthewhoffman** [comment]
@xylar , based on this discussion, I agree that is the best solution, despite the slightly longer name.  If we want to avoid the extra empty directory level (so tab completion works), we could always replace the / with a . or _ though that may be confusing.  In any case, I'm good with this solution if @mark-petersen  is.  Let me know if you want me to contribute by making the associated revision since you did everything else.

**Comment by mark-petersen** [comment]
I agree that we should have the exact organization name to avoid confusion. So the current proposal is that we could eventually have:
```
├── E3SM-Ocean-Discussion
│   └── E3SM
├── E3SM-Omega
│   └── E3SM
├── E3SM-Project
│   └── E3SM
├── E3SM-Seaice-Discussion
│   └── E3SM
```
I think that is a lot of extra directories at the highest level. My preference is to switch the order to `repo/organization`:
```
├── E3SM
│   ├── E3SM-Ocean-Discussion
│   ├── E3SM-Omega
│   ├── E3SM-Project
│   ├── E3SM-Seaice-Discussion
│   └── MALI-Dev
```
That is more logical to me, and neater. At the top level it says 'here is the E3SM code' and one directory down it says 'choose your fork'.
```

**Comment by mark-petersen** [comment]
Would we ever have repositories other than E3SM as submodules in compass anyway? If not, just 
```
E3SM-Project
MALI-Dev
```
at the top level would be sufficient. There is not a reason to include the Discussion forks, because it would just be tracking E3SM-Project/E3SM:master. Everyone will be developing on branches on their personal forks, so those could be anywhere on disk, not necessarily here as a submodule. 

Also, the purpose of a submodule is to track which version of E3SM is compatible with compass. So no need to do that with discussion forks.

**Comment by xylar** [comment]
@mark-petersen, thanks.  I agree, let's eliminate the `E3SM` directory and just have the organization names.  I think that's clear enough.  I also agree that we don't need the discussion organizations for the reasons you said.

@matthewhoffman, are you good with that plan?  If so, I'll start making those changes.

**Comment by matthewhoffman** [comment]
Agreed on all accounts.

**Comment by xylar** [comment]
@matthewhoffman and @mark-petersen, this has been modified based on our discussion above and is ready for you to take another look.

**Comment by xylar** [comment]
There is, of course, very little chance that I didn't miss anything in the documentation.  @matthewhoffman, you said you would go through at some point and make a PR with a lot of suggested changes.  I don't think we're quite at the point where it's time for that.  Let's get #117 in first.  But I'm hoping this change is one you can have a eye out for in that process.

**Comment by xylar** [comment]
## Testing

I built MPAS-Ocean and MALI in the new submodules on my Linux laptop with gnu.  I successfully set up the `nightly` and `sia_integration` suites from the default locations (from each component's config file).  The suites ran as normal (known errors in the `enthalpy_benchmark/A` and RK4 restart tests).

I didn't check against a benchmark because I'm not 100% sure the code is the same as before the move to these modules and any diffs in the code itself aren't within the scope of this PR.  But I can check if anyone is concerned.

**Review by matthewhoffman — APPROVED** [review]
Looks good, @xylar .  The documentation are impressively thorough.

**Review by mark-petersen — APPROVED** [review]
Looks good. I did a quick retrieval on the submodules, compiled MPAS-O and ran. It all worked fine.

**Comment by xylar** [comment]
Thank @mark-petersen and @matthewhoffman!

**Pull request merged**
