### PR TITLE
Update metapackage to 0.1.12

### PR DESCRIPTION
**Pull request by xylar**
Update `geometric_features` and `mpas_tools` versions and add `lxml`, `matplotlib` and `cmocean` as dependencies.

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen, I need to release the next compass metapackage before the beta testing for the next e3sm-unified starts on Tuesday (Dec 1st).  I have created test compass environments on Grizzly:
```
source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/etc/profile.d/conda.sh
conda activate test_compass_0.1.12
```
and Anvil:
```
source /lcrc/soft/climate/e3sm-unified/base/etc/profile.d/conda.sh
conda activate test_compass_0.1.12
```

I wasn't going to set up test environments on any other machines because there will be a month of testing of e3sm-unified anyway.  Would you have a chance to run whatever you normally test in compass with these environments by COB on Monday?

**Comment by xylar** [comment]
## Testing

I ran the nightly regression suite on Anvil with the `test_compass_0.1.12` environment and all tests ran successfully.  I also ran the full spin-up and created filed for E3SM for the EC15to60 mesh.  This ensures that the the MOC aggregation changes in MPAS-Tools are working as expected.

**Comment by xylar** [comment]
@mark-petersen, I'm going to go ahead with this tomorrow so it can be part of beta testing of E3SM-Unified.  If you have a chance to test, please review.  Otherwise, I'll follow up with you once the release is deployed tomorrow.

**Comment by mark-petersen** [comment]
Tested on grizzly and badger, from compass master, with the nightly regression suite. Looks great, thanks.

**Comment by xylar** [comment]
@mark-petersen, thanks very much for testing!

**Pull request merged**
