### PR TITLE
Update to 1.2.0-alpha.6

### LINKED ISSUE #607: Need spack clone for each spack environment
Different users don't have permission to use the same git clone of a spack repo, so we need to clone the spack repo for each environment.

### PR DESCRIPTION
**Pull request by xylar**
This merge updates compass to v. 1.2.0-alpha.6.  This update:
* Brings in a new `mache` with support for Intel on Perlmutter and which allows for spack environment builds on non-E3SM machines
* Updates to a new `pyremap` that supports specifying the NetCDF format and (where appropriate) the xarray NetCDF engine
* Names spack clones the same as the spack environment that will be created in them (to avoid multiple developers trying to use the same clone of spack)
* Adds support for deploying on supported machines that aren't part of `mache` (non-E3SM machines), including documentation and some examples (2 of my laptops)
* Update versions of HDF5, NetCDF-C, NetCDF-Fortran, Parallel-NetCDF, ESMF and PETSc in spack environments
* Drops the `--with_netlib_lapack` flag, since we currently require that library always wehen PETSc is installed.

Checklist
* [x] Developer's Guide has been updated
* [x] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [x] The `E3SM-Project` submodule has been updated with relevant E3SM changes
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

closes #607 

## Testing

MPAS-Ocean with `pr`:
- [x] Anvil
  - [x] intel and impi
  - [x] gnu and openmpi
- [x] Chicoma
  - [x] gnu and mpich - hanging on `cosine_bell/QU90/forward` in `pr` suite but runs fine when running `cosine_bell` on its own (even on same node count).
- [x] Chrysalis 
  - [x] intel and openmpi
  - [x] gnu and openmpi
- [x] Compy 
  - [x] intel and impi - still seeing https://github.com/MPAS-Dev/compass/issues/502
- [x] Perlmutter
  - [x] gnu and mpich

MALI with `full_integration` - as discussed with @matthewhoffman, validation failures in `landice/circular_shelf/decomposition_test` indicate that thresholds need to be adjusted.  Check marks indicate that all *other* tests are passing:
- [x] Chicoma
  - [x] gnu and mpich
- [x] Chrysalis 
  - [x] gnu and openmpi
- [x] Perlmutter
  - [x] gnu and mpich

MPAS-Ocean with `nonhydro`:
- [x] Anvil
  - [x] intel and impi
- [x] Chicoma
  - [x] gnu and mpich
- [x] Chrysalis
  - [x] intel and openmpi
- [x] Compy
  - [x] intel and impi
- [x] Perlmutter
  - [x] gnu and mpich

## Deployed

MPAS-Ocean with `pr`:
- [x] Anvil
  - [x] intel and impi
  - [x] intel and openmpi
  - [x] gnu and openmpi
  - [x] gnu and mvapich
- [x] Chicoma
  - [x] gnu and mpich - Requires new mache, see #656; long time but eventually finishes (~30 minutes).
- [x] Chrysalis
  - [x] intel and openmpi
  - [x] gnu and openmpi
- [x] Compy
  - [x] intel and impi - #502 is still an issue
- [x] Perlmutter 
  - [x] gnu and mpich

MALI with `full_integration` (passing excep #654):
- [x] Chicoma
  - [x] gnu and mpich
- [x] Chrysalis 
  - [x] gnu and openmpi
- [x] Perlmutter
  - [x] gnu and mpich

MPAS-Ocean with `nonhydro`:
- [x] Anvil
  - [x] intel and impi
  - [x] gnu and openmpi
- [x] Chicoma
  - [x] gnu and mpich
- [x] Chrysalis
  - [x] intel and openmpi
  - [x] gnu and openmpi
- [x] Compy
  - [x] intel and impi
- [x] Perlmutter
  - [x] gnu and mpich

### CODE REVIEW

**Comment by xylar** [comment]
This needs https://github.com/E3SM-Project/E3SM/pull/5732 and an equivalent update to MALI-Dev.

**Comment by xylar** [comment]
`mache` will need to be updated because of https://github.com/E3SM-Project/E3SM/issues/5755

**Comment by xylar** [comment]
`ESMF_RegridWeightGen` is giving me trouble with intel on Perlmutter, so it seems some more debugging is needed there.

A few other tests are also failing both for MPAS-Ocean and MALI so that will also need some debugging...

**Comment by xylar** [comment]
Still need to release mache 1.16.0 and then update mache here before we deploy.

**Comment by xylar** [comment]
I re-tested on Chicoma and (after a fix in the Spack branch) the PR suite ran successfully.  I think we're set once I can release `mache`.

**Comment by xylar** [comment]
@matthewhoffman, this is ready to merge as soon as you're happy.

**Comment by xylar** [comment]
@matthewhoffman, maybe this is something you'll be able to test and approve once LCRC is back up?

**Review by matthewhoffman — APPROVED** [review]
@xylar , thanks for the substantial amount of work in putting this together!  My MALI full_integration tests look good, and I blessed the small changes expected from the update of the Albany version.  I also tested with #634 and the depth-integrated solver works as expected with the new version of Albany in this PR.  

One thing that surprised me, though, is I forgot to test merge https://github.com/E3SM-Project/E3SM/pull/5732 into MALI-Dev/develop when I did my testing, but I did not run into any problems compiling.  Does that surprise you?  Assuming that's not an indication of anything amiss, I'm approving this.

**Comment by xylar** [comment]
As we discussed on slack,
> One thing that surprised me, though, is I forgot to test merge https://github.com/E3SM-Project/E3SM/pull/5732 into MALI-Dev/develop when I did my testing, but I did not run into any problems compiling. Does that surprise you? Assuming that's not an indication of anything amiss, I'm approving this.

The answer is that MALI is so far out of date that ADIOS support was never added so #5732 isn't even needed :wink:

**Comment by xylar** [comment]
Thank you @matthewhoffman!!!

**Pull request merged**
