### PR TITLE
Add jigsaw spherical mesh steps

### PR DESCRIPTION
**Pull request by xylar**
There is a base class and classes for creating either icosahedral subdivision meshes or meshes from a map of cell width.

The `QuasiUniformSphericalMeshStep` class creates a quasi-uniform base mesh, and allows the `build_cell_width_lat_lon()` an `make_jigsaw_mesh()` methods to be overridden to change the functionality (e.g. to build a map of cell width that varies with space).

The `IcosahedralMeshStep` class creates a subdivided icosahedral mesh defined either by its approximate cell width or the number of subdivisions.

This merge also updates the `global_convergence` test group to make use of these new classes.  There are now `qu` and `icos` versions of the `cosine_bell` test case.

The documentation has been updated based on these changes.

### CODE REVIEW

**Comment by xylar** [comment]
@dengwirda, I'm trying to cut down on the scope of this work to make it a bit easier to review.  I still feel the need to have a demonstration of how this works, in this case the cosine-bell test case.  But I'm not trying to alter the global ocean at the same time.  I know it can be done, though, since I did it in https://github.com/MPAS-Dev/compass/pull/402.

What I'm mostly asking for in a review is to know if the new classes I've added address your concerns about the JIGSAW functionality not being sufficiently exposed, or if you still have concerns.

**Comment by xylar** [comment]
@dengwirda, it doesn't seem like you're finding time to look at this.  Let me know when you think you might have time.

@mark-petersen, in the meantime, I'd like to try to make headway on this.  Would you be willing to have a look?  I mostly want to make sure you're good with the basic ideas behind it.  We could have a WebEx or Slack chat if that would help.

**Comment by dengwirda** [comment]
@xylar I've run this on cori, and can confirm that overriding the `make_jigsaw_mesh` and `build_cell_width` calls allows for custom workflows. Thanks for adding this, it will be useful for me.
If you're interested to learn about various jigsaw workflows you may be interested in the [tutorial](https://github.com/dengwirda/jigsaw-geo-tutorial), the [example problems](https://github.com/dengwirda/jigsaw-geo-python) and the list of [config. options](https://github.com/dengwirda/jigsaw/wiki/JIG-File-Format).

**Comment by xylar** [comment]
@dengwirda, great, thanks!  Could you approve the PR based on your testing?

**Comment by xylar** [comment]
And thank you for linking the tutorials and example.  If you want to update the compass documentation to point to these more explicitly, I think that would also be great!

**Review by dengwirda — APPROVED** [review]
Approved based on testing `jigsawpy.lib.marche` and `jigsawpy.cmd.jigsaw` workflows on cori.

**Comment by xylar** [comment]
@mark-petersen, I'm taking you off as a reviewer for now since I think @dengwirda's review is plenty.

@dengwirda, thank you again for your review!

**Pull request merged**
