### PR TITLE
Port cosine bell initial state

### PR DESCRIPTION
**Pull request by cbegeman**
This PR moves the generation of an initial state for the ocean global cosine bell test case from init mode to the initial state compass step. 

Checklist
* [X] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by cbegeman** [comment]
### Testing:

I have run both `icos` and `qu` tests on chrysalis with intel compiler and found that the changes in the initial state `normalVelocity` and `debugTracers` fields are O(1e-8). These diffs are maintained at the end of the forward simulation. This difference can be due to such differences in precision as the value of pi used by numpy vs the fortran code.

**Review by xylar — APPROVED** [review]
This looks excellent to me and the small differences seem at the expected level for differences in order of operations and the like.

**Comment by cbegeman** [comment]
Thanks, @xylar, for the review!

**Comment by xylar** [comment]
@cbegeman, would you be willing to rebase this and then fix any issues that pre-commit might suggest when CI runs again here?

**Comment by xylar** [comment]
@cbegeman, you may have figured this out but you can run:
```
pre-commit run --show-diff-on-failure --color=always --files compass/ocean/tests/global_convergence/cosine_bell/__init__.py compass/ocean/tests/global_convergence/cosine_bell/cosine_bell.cfg compass/ocean/tests/global_convergence/cosine_bell/init.py
```
locally (and a few times) to find out what linting is needed.  Then, just make a commit to fix those issues.

**Comment by cbegeman** [comment]
@xylar Thanks! That would definitely save me some time!

**Comment by xylar** [comment]
@cbegeman, since we already ported this over to polaris, I'm tempted to merge.  Would you like to wait to hear from @lconlon and @alicebarthel first?

**Comment by cbegeman** [comment]
@xylar Let's go ahead and merge. Thanks for reviewing!

**Comment by xylar** [comment]
@cbegeman, thanks for adding this!

**Comment by alicebarthel** [comment]
Thanks @cbegeman @xylar , this looks good to me (and I appreciate the opportunity to read through the files) and I'm glad you moved ahead with the merge.

**Pull request merged**
