### PR TITLE
Add a sigma vertical coordinate to ocean framework

### PR DESCRIPTION
**Pull request by xylar**
This merge also adds ISOMIP+ test cases that demonstrate the usage of the coordinate.

In the process, a small bug was found in the ISOMIP+ visualization in which the colormap bounds were incorrectly including zero even for fields (like salinity) where this is not appropriate.  This has also been fixed here for convenience.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the `performance` and then 1 month of the `simulation` step in the `2km/sigma/Ocean0` test case.

The results look as expected, e.g. here is a cross section of potential temperature:
sectionTemp_0001

And here is the overturning streamfunction:
osf_0001

**Comment by xylar** [comment]
@cbegeman, this is ready for you to review.  I think all you need to do is describe the testing you've already done (since I believe you are already using this coordinate and the sigma versions of the ISOMIP+ test cases).

**Review by cbegeman — APPROVED** [review]
Approving based on testing on chrys with intel-mpi. I ran both the included 10-layer sigma `Ocean0` case and a 3-layer sigma `time_varying_Ocean0` case.

**Comment by xylar** [comment]
Thanks for the review, @cbegeman!

**Pull request merged**
