### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by xylar**
This merge brings in documentation from https://github.com/MPAS-Dev/MPAS-Model/tree/ocean/develop/docs/compass

It moves the outdated documentation in the `docs` folder to `docs/old_docs`, with the idea that it could be deleted once everyone is good with the new documentation format using sphinx.

The merge also adds the YAML file that will be needed for future integration of Azure Pipelines for automatically building and uploading the documentation.  This is analogous to what has been done for MPAS-Model, MPAS-Tools, MPAS-Analysis, pyremap and geometric_features.

### CODE REVIEW

**Comment by xylar** [comment]
@mark-petersen and @matthewhoffman, I think all I need as a review is you to make sure you're okay with this as a starting point for better documentation in the future, and that you're okay with me moving the old, outdated documentation to `docs/old_docs`

**Review by mark-petersen — APPROVED** [review]
Approved by visual inspection. I am excited to have read-the-docs match our test cases here and build out the documentation. Ditto for the MPAS-Model repo.

**Review by matthewhoffman — APPROVED** [review]
@xylar , this looks fine to me.  I agree that having a more robust documentation system would be a real asset.  I don't have the experience to evaluate this approach, but I know you've vetted this approach for other parts of the project.

**Comment by xylar** [comment]
Thanks to both of you!

**Pull request merged**
