### PR TITLE
Threshold Levels for circularshelf_decompostion_test

### PR DESCRIPTION
**Pull request by yariseidenbenz**
Increased threshold slightly to allow test to pass

### CODE REVIEW

**Review by matthewhoffman — APPROVED** [review]
Tested on Badger and confirmed this fixes the failing test.  The threshold is arbitrary to allow known differences on different numbers of procs but still small enough to flag if big difference were to appear.

**Comment by matthewhoffman** [comment]
@xylar , would you prefer to merge this PR, or should I feel free to merge myself?

**Comment by xylar** [comment]
@matthewhoffman, for future reference, you can merge any changes to land-ice test cases yourself.  But I'm happy to take care of this one.

**Comment by matthewhoffman** [comment]
@xylar , will do - thanks for merging this this time.

**Pull request merged**
