### PR TITLE
Fix DISMF dataset name in global ocean forward runs

### PR DESCRIPTION
**Pull request by xylar**
This got missed in the pull request (#778) that switched to Paolo et al. (2023) melt rates.

Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I was able to run the QUwISC240 `mesh`, `init` and `performance_test` test cases with this branch on Chrysalis, whereas the `data_ice_shelf_melt` step failed without this fix.

**Comment by xylar** [comment]
I am not currently able to run the `pr` suite because of missing cache files, an issue I will fix in a separate PR.

**Comment by xylar** [comment]
@cbegeman. this one just needs a very quick review by inspection, as I think it's an obvious fix.

**Comment by xylar** [comment]
Shoot, I merged this by mistake as part of #791

**Comment by cbegeman** [comment]
@xylar That's ok. It's an obvious change. Thanks

**Pull request merged**
