### PR TITLE
Update the `E3SM-Project` submodule

### LINKED ISSUE #304: Coriolis parameter not being initialized in Global Ocean init step
Following difficulties that @ytakano3 is having spinning up his mesh focused on the Kuroshio Current, I tried rerunning the WC14 dynamic adjustment and got some pretty crazy results.

As an example, here is the SST in the initial condition:
sst_ic
And here is the same after 30 days of dynamic adjustment:
sst_30_days
Note that SSTs reach 60 C in several coastal locations after 30 days!

Similarly, here is the temperature in layer 11 in the initial condition:
temp_layer_11_ic
and after 30 days:
temp_layer_11_30_days

### PR DESCRIPTION
**Pull request by xylar**
commit hash: 44814ae3ce06ec1d175fc03a6c4471f9d3fad274

This update includes the following MPAS-Ocean PRs:
* Corrected coupling of ice biogeochemistry for MARBL
  https://github.com/E3SM-Project/E3SM/pull/4641
* GPU port of ocean vmix routine (non-bit-for-bit in compass)
  https://github.com/E3SM-Project/E3SM/pull/4680
* Fix filename interval for 2 analysis member restarts
  https://github.com/E3SM-Project/E3SM/pull/4687
* fix calculation of the ML-averaged Brunt-Vaisala frequency
  https://github.com/E3SM-Project/E3SM/pull/4715
* Fix interface locations for 60-layer PHC grid
  https://github.com/E3SM-Project/E3SM/pull/4729
* Update PGI compiler runs of E3SM on GPUs
  https://github.com/E3SM-Project/E3SM/pull/4748
* Initialize Coriolis param in its own subroutine
  https://github.com/E3SM-Project/E3SM/pull/4750
* Add mode specification to conservation check streams
  https://github.com/E3SM-Project/E3SM/pull/4769

And the following MPAS framework PRS:
* add -ffpe-summary=none to stand-alone MPAS Makefile for gnu
  https://github.com/E3SM-Project/E3SM/pull/4643
* Fix missing dependency in one case of gen_f90_targets
  https://github.com/E3SM-Project/E3SM/pull/4736
* new reproducible global sum module for MPAS components
  https://github.com/E3SM-Project/E3SM/pull/4700

closes #304

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

The E3SM PR https://github.com/E3SM-Project/E3SM/pull/4680 produces non-bit-for-bit results for the `pr` test suite on Chrysalis with Intel and Intel-MPI.

The differences in output variables are significant for some tests, which is worrisome!

`ocean/baroclinic_channel/10km/threads_test`
```
normalVelocity       Time index: 0, 1, 2
0:  l1: 3.38813178901720e-21  l2: 3.38813178901720e-21  linf: 3.38813178901720e-21
1:  l1: 3.38813178901720e-20  l2: 2.79392504792617e-20  linf: 2.71050543121376e-20
2:  l1: 1.73472347597681e-18  l2: 1.73472347597681e-18  linf: 1.73472347597681e-18
```
`ocean/baroclinic_channel/10km/decomp_test`
```
normalVelocity       Time index: 0, 1, 2
0:  l1: 3.38813178901720e-21  l2: 3.38813178901720e-21  linf: 3.38813178901720e-21
1:  l1: 3.38813178901720e-20  l2: 2.79392504792617e-20  linf: 2.71050543121376e-20
2:  l1: 1.73472347597681e-18  l2: 1.73472347597681e-18  linf: 1.73472347597681e-18
```
`ocean/baroclinic_channel/10km/restart_test`
```
normalVelocity       Time index: 0
0:  l1: 3.38813178901720e-20  l2: 2.79392504792617e-20  linf: 2.71050543121376e-20
```
`ocean/global_ocean/EC30to60/PHC/performance_test`
```
temperature          Time index: 0, 1, 2, 3
2:  l1: 7.31411718646484e-08  l2: 1.83505813823141e-08  linf: 9.74073444126589e-09
3:  l1: 1.33872814312072e-03  l2: 2.09127536444941e-04  linf: 1.46209104059380e-04
salinity             Time index: 0, 1, 2, 3
2:  l1: 2.36493384875303e-08  l2: 5.46866400601553e-09  linf: 2.82363998849178e-09
3:  l1: 2.22048229055360e-04  l2: 3.04693913780335e-05  linf: 1.83430411198060e-05
layerThickness       Time index: 0, 1, 2, 3
2:  l1: 4.85123052840208e-12  l2: 2.67523114450455e-13  linf: 3.01980662698043e-14
3:  l1: 1.37929223598121e-10  l2: 1.84328390575566e-12  linf: 8.75743921824323e-13
 normalVelocity       Time index: 0, 1, 2, 3
1:  l1: 5.44878378898368e-15  l2: 1.13113902237797e-16  linf: 2.77555756156289e-17
2:  l1: 1.08912509907275e-07  l2: 1.54783686807343e-08  linf: 5.17246761394530e-09
3:  l1: 1.26143431972967e-04  l2: 7.93783037375424e-06  linf: 2.23004445490393e-06
```
`ocean/global_ocean/ECwISC30to60/PHC/performance_test`
```
temperature          Time index: 0, 1, 2, 3
2:  l1: 7.31407925744890e-08  l2: 1.83505813801927e-08  linf: 9.74073444126589e-09
3:  l1: 1.33851344954417e-03  l2: 2.09127531942238e-04  linf: 1.46209104059380e-04
salinity             Time index: 0, 1, 2, 3
2:  l1: 2.36558115318530e-08  l2: 5.46866401150399e-09  linf: 2.82363998849178e-09
3:  l1: 2.21976619016573e-04  l2: 3.04693872350800e-05  linf: 1.83430411198060e-05
layerThickness       Time index: 0, 1, 2, 3
2:  l1: 5.45519185379817e-12  l2: 2.84954436175697e-13  linf: 3.01980662698043e-14
3:  l1: 1.44762091203177e-10  l2: 1.85524045334782e-12  linf: 8.75743921824323e-13
normalVelocity       Time index: 0, 1, 2, 3
1:  l1: 5.37985243302458e-15  l2: 1.11325219493148e-16  linf: 2.77555756156289e-17
2:  l1: 1.08911560148595e-07  l2: 1.54783686792196e-08  linf: 5.17246761394530e-09
3:  l1: 1.26042816454341e-04  l2: 7.93781811774144e-06  linf: 2.23004445490393e-06
ssh                  Time index: 0, 1, 2
1:  l1: 5.30420152244915e-12  l2: 9.57833614346478e-13  linf: 8.81072992342524e-13
2:  l1: 1.33585587036578e-10  l2: 4.62690390807070e-12  linf: 8.84625706021325e-13
landIceFrictionVelocity Time index: 0, 1, 2
1:  l1: 6.98536539809474e-10  l2: 2.11104591828438e-10  linf: 1.32276088086331e-10
2:  l1: 6.06511903744871e-07  l2: 1.43374091689171e-07  linf: 6.64915306030668e-08
topDrag              Time index: 0, 1, 2
1:  l1: 5.32275504054602e-18  l2: 2.79735269380422e-18  linf: 2.49366499671666e-18
2:  l1: 1.34674381437150e-14  l2: 2.03677407770247e-15  linf: 8.44691748188089e-16
topDragMagnitude     Time index: 0, 1, 2
1:  l1: 4.55364912443912e-18  l2: 3.39408966264276e-18  linf: 3.03576608295941e-18
2:  l1: 4.84605850329802e-15  l2: 1.33689875004202e-15  linf: 1.05666343730437e-15
landIceFreshwaterFlux Time index: 0, 1, 2
2:  l1: 1.89735380184963e-19  l2: 1.76703335264836e-19  linf: 1.76182853028894e-19
heatFluxToLandIce    Time index: 0, 1, 2
2:  l1: 7.21644966006352e-16  l2: 6.68442777728834e-16  linf: 6.66133814775094e-16
landIceBoundaryLayerTemperature Time index: 0, 1, 2
1:  l1: 1.91859944385204e-08  l2: 7.96678861066005e-09  linf: 5.40834577122951e-09
2:  l1: 8.41022966193866e-06  l2: 2.58087808208966e-06  linf: 1.61673502852011e-06
landIceBoundaryLayerSalinity Time index: 0, 1, 2
1:  l1: 6.88146073457574e-09  l2: 2.77582399564112e-09  linf: 1.84152781912417e-09
2:  l1: 9.51822571337857e-06  l2: 3.12396247451155e-06  linf: 2.22908725788784e-06
landIceHeatTransferVelocity Time index: 0, 1, 2
1:  l1: 7.68390192578826e-12  l2: 2.32215051423762e-12  linf: 1.45503697117225e-12
2:  l1: 6.67163094197272e-09  l2: 1.57711500858021e-09  linf: 7.31406836632705e-10
landIceSaltTransferVelocity Time index: 0, 1, 2
1:  l1: 2.16546325599573e-13  l2: 6.54424234875922e-14  linf: 4.10055872839265e-14
2:  l1: 1.88018690167912e-10  l2: 4.44459684236838e-11  linf: 2.06123744870495e-11
accumulatedLandIceMass Time index: 0, 1, 2
2:  l1: 3.33066907387547e-16  l2: 2.83052443350184e-16  linf: 2.77555756156289e-16
accumulatedLandIceHeat Time index: 0, 1, 2
2:  l1: 1.36424205265939e-12  l2: 1.15938280796235e-12  linf: 1.13686837721616e-12
```
`ocean/ice_shelf_2d/5km/z-star/restart_test`
```
temperature          Time index: 0
0:  l1: 2.63788990650937e-13  l2: 1.08586395753452e-14  linf: 1.88737914186277e-15
salinity             Time index: 0
0:  l1: 2.06270556191157e-11  l2: 4.57569661508385e-13  linf: 4.26325641456060e-14
layerThickness       Time index: 0
0:  l1: 2.63266297650944e-10  l2: 9.12484604073270e-12  linf: 1.73372427525464e-12
normalVelocity       Time index: 0
0:  l1: 5.64016623381445e-10  l2: 8.82647166888918e-12  linf: 3.46273675412529e-13
temperature          Time index: 0
0:  l1: 2.63788990650937e-13  l2: 1.08586395753452e-14  linf: 1.88737914186277e-15
salinity             Time index: 0
0:  l1: 2.06270556191157e-11  l2: 4.57569661508385e-13  linf: 4.26325641456060e-14
layerThickness       Time index: 0
0:  l1: 2.63266297650944e-10  l2: 9.12484604073270e-12  linf: 1.73372427525464e-12
normalVelocity       Time index: 0
0:  l1: 5.64016623381445e-10  l2: 8.82647166888918e-12  linf: 3.46273675412529e-13
ssh                  Time index: 0
0:  l1: 1.95726101992477e-10  l2: 1.68841520572276e-11  linf: 3.86535248253495e-12
landIcePressure      Time index: 0
0:  l1: 1.52969732880592e-06  l2: 1.72467324968884e-07  linf: 5.21540641784668e-08
landIceFrictionVelocity Time index: 0
0:  l1: 5.63151955623731e-14  l2: 8.23882721751003e-15  linf: 3.31332183911570e-15
topDrag              Time index: 0
0:  l1: 6.95205620756240e-13  l2: 6.13655605636751e-14  linf: 2.03731346029579e-14
topDragMagnitude     Time index: 0
0:  l1: 2.83813567174348e-13  l2: 4.44912960285689e-14  linf: 1.82369310625097e-14
landIceFreshwaterFlux Time index: 0
0:  l1: 1.80964184609556e-14  l2: 2.03020424356250e-15  linf: 6.67434857382077e-16
landIceHeatFlux      Time index: 0
0:  l1: 6.18862827650446e-09  l2: 6.95154884726944e-10  linf: 2.28851604333613e-10
heatFluxToLandIce    Time index: 0
0:  l1: 7.63415997084849e-11  l2: 8.95023848050162e-12  linf: 3.03934655221383e-12
landIceBoundaryLayerTemperature Time index: 0
0:  l1: 3.46389583683049e-14  l2: 4.10332181845526e-15  linf: 1.22124532708767e-15
landIceBoundaryLayerSalinity Time index: 0
0:  l1: 1.75504055732745e-12  l2: 1.28488447046672e-13  linf: 2.13162820728030e-14
  FAIL /lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20211129/pr_before_fix-two-analysis/ocean/ice_shelf_2d/5km/z-landIceHeatTransferVelocity Time index: 0
0:  l1: 6.19452134986015e-16  l2: 9.06284135275253e-17  linf: 3.64495217862471e-17
  FAIL /lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20211129/pr_before_fix-two-analysis/ocean/ice_shelf_2d/5km/z-landIceSaltTransferVelocity Time index: 0
0:  l1: 1.74598901417529e-17  l2: 2.55405055450829e-18  linf: 1.02713332766425e-18
landIceInterfaceTemperature Time index: 0
0:  l1: 1.05249142734465e-13  l2: 1.22104345167062e-14  linf: 3.55271367880050e-15
landIceInterfaceSalinity Time index: 0
0:  l1: 4.10338429901458e-13  l2: 4.41952441030392e-14  linf: 1.06581410364015e-14
accumulatedLandIceMass Time index: 0
0:  l1: 5.42826894545101e-12  l2: 6.09054683331078e-13  linf: 2.00284233642378e-13
accumulatedLandIceHeat Time index: 0
0:  l1: 2.28849330596859e-08  l2: 2.68432436133704e-09  linf: 9.11768438527361e-10
```
`ocean/isomip_plus/2km/z-star/Ocean0/performance`
```
temperature          Time index: 0
0:  l1: 4.30238510425563e-08  l2: 1.49606686860859e-10  linf: 4.07185396511522e-12
salinity             Time index: 0
0:  l1: 1.39156810519125e-08  l2: 4.73159290777263e-11  linf: 1.27187149701058e-12
layerThickness       Time index: 0
0:  l1: 1.42320138660224e-09  l2: 1.20526192677610e-11  linf: 1.15107923193136e-12
normalVelocity       Time index: 0
0:  l1: 1.21006451383304e-07  l2: 2.28257588763759e-10  linf: 3.26475109967139e-12
ssh                  Time index: 0
0:  l1: 1.04839870118667e-09  l2: 2.92451526662588e-11  linf: 3.97903932025656e-12
landIcePressure      Time index: 0
0:  l1: 7.69903999753296e-06  l2: 2.65556945306166e-07  linf: 4.09781932830811e-08
landIceFrictionVelocity Time index: 0
0:  l1: 6.99239494431070e-13  l2: 2.38540934996390e-14  linf: 3.99571868647808e-15
  FAIL /lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20211129/pr_before_fix-two-analysis/ocean/isomip_plus/2km/z-star/Ocean0/performance/land_ice_fluxes.nc
       /lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20211212/pr_baseline/ocean/isomip_plus/2km/z-star/Ocean0/performance/land_ice_fluxes.nc
topDrag              Time index: 0
0:  l1: 2.35193667530260e-12  l2: 5.42472338699142e-14  linf: 6.61264095306387e-15
  FAIL /lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20211129/pr_before_fix-two-analysis/ocean/isomip_plus/2km/z-star/Ocean0/performance/land_ice_fluxes.nc
       /lcrc/group/e3sm/ac.xylar/compass_1.0/chrysalis/test_20211212/pr_baseline/ocean/isomip_plus/2km/z-star/Ocean0/performance/land_ice_fluxes.nc
topDragMagnitude     Time index: 0
0:  l1: 6.25037620545289e-13  l2: 2.44565222090265e-14  linf: 4.10927234690346e-15
landIceFreshwaterFlux Time index: 0
0:  l1: 1.49301758463176e-13  l2: 6.98556670056392e-15  linf: 1.14247803925660e-15
landIceHeatFlux      Time index: 0
0:  l1: 5.07232826851833e-08  l2: 2.37260363523750e-09  linf: 3.87984755434445e-10
heatFluxToLandIce    Time index: 0
0:  l1: 4.53552842852312e-10  l2: 2.08836049412938e-11  linf: 3.37718741860726e-12
landIceBoundaryLayerTemperature Time index: 0
0:  l1: 5.64787118982613e-11  l2: 1.44010483072019e-12  linf: 1.82631687550838e-13
landIceBoundaryLayerSalinity Time index: 0
0:  l1: 1.12109432848229e-10  l2: 1.67751299984631e-12  linf: 8.52651282912120e-14
landIceHeatTransferVelocity Time index: 0
0:  l1: 1.35653393764290e-14  l2: 4.62769727069803e-16  linf: 7.75170672009245e-17
landIceSaltTransferVelocity Time index: 0
0:  l1: 3.87576653916913e-16  l2: 1.32219842556549e-17  linf: 2.21477939883318e-18
landIceInterfaceTemperature Time index: 0
0:  l1: 1.04787289956221e-11  l2: 3.22814522339048e-13  linf: 3.95239396766556e-14
landIceInterfaceSalinity Time index: 0
0:  l1: 1.84147808113266e-10  l2: 5.66348583334609e-12  linf: 6.96331881044898e-13
accumulatedLandIceMass Time index: 0
0:  l1: 1.44344845104394e-10  l2: 5.44068644185730e-12  linf: 9.19042619784705e-13
accumulatedLandIceHeat Time index: 0
0:  l1: 4.47586998575389e-07  l2: 1.64047052772792e-08  linf: 2.72711986326613e-09
```

**Comment by mark-petersen** [comment]
For this output,
```
temperature          Time index: 0, 1, 2, 3
2:  l1: 7.31411718646484e-08  l2: 1.83505813823141e-08  linf: 9.74073444126589e-09
3:  l1: 1.33872814312072e-03  l2: 2.09127536444941e-04  linf: 1.46209104059380e-04
```
I'm guessing that timestep 1 was bfb, so that line of printing is omitted? Is time index 0 before or after the first timestep? (normalVelocity differs at time 0, so I would assume it is after). That tells us that the vertical tracer diffusion is not a problem, just the momentum (ocn_vel_vmix_tend_implicit) part.

**Comment by mark-petersen** [comment]
Actually, I see a likely culprit. Rayleigh drag is off for E3SM, but on for spin-up and many tests in COMPASS. See these lines:
```
compass/ocean/tests/global_ocean/mesh/qu240/namelist.rk4:9:config_Rayleigh_friction = .true.
compass/ocean/tests/global_ocean/mesh/qu240/namelist.rk4:10:config_Rayleigh_damping_depth_variable = .true.
compass/ocean/tests/global_ocean/mesh/qu240/namelist.rk4:11:config_Rayleigh_bottom_friction = .true.
compass/ocean/tests/global_ocean/mesh/qu240/namelist.split_explicit:10:config_Rayleigh_friction = .true.
compass/ocean/tests/global_ocean/mesh/qu240/namelist.split_explicit:11:config_Rayleigh_damping_depth_variable = .true.
compass/ocean/tests/global_ocean/mesh/qu240/namelist.split_explicit:12:config_Rayleigh_bottom_friction = .true.
```
in E3SM these same flags are set to false:
```
components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml:188:<config_Rayleigh_friction>.false.</config_Rayleigh_friction>
components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml:190:<config_Rayleigh_damping_depth_variable>.false.</config_Rayleigh_damping_depth_variable>
components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml:191:<config_Rayleigh_bottom_friction>.false.</config_Rayleigh_bottom_friction>
```
as they should be for simulations.

@xylar, could you change those three flags to false and repeat your COMPASS tests?

**Comment by mark-petersen** [comment]
There are two different routines for vel_vmix with or without Rayleigh drag:

`subroutine ocn_vel_vmix_tend_implicit`
https://github.com/E3SM-Project/E3SM/blob/679cebf91bcbd032351e429293333eb395ecb0d3/components/mpas-ocean/src/shared/mpas_ocn_vmix.F#L215

`subroutine ocn_vel_vmix_tend_implicit_Rayleigh`
https://github.com/E3SM-Project/E3SM/blob/679cebf91bcbd032351e429293333eb395ecb0d3/components/mpas-ocean/src/shared/mpas_ocn_vmix.F#L378

and the first is run for E3SM tests, and the second for COMPASS tests. So most likely there are changes causing this in the second.

**Comment by xylar** [comment]
@mark-petersen, thanks a lot of these thoughts.  I'll check on which configurations have Rayleigh damping on and turn it off except where it really should be on.

I doubt that's the full explanation because so many tests fail above (`baroclinic_channel` and `ice_shelf_2d` in addition to `global_ocean`) but I need to make sure Rayleight damping isn't accidentally on for those tests.

**Comment by xylar** [comment]
@mark-petersen, I tried to figure out what cause the change in Rayleigh friction flags (because these were not on for legacy COMPASS) and it turns out to be this PR of yours: https://github.com/MPAS-Dev/compass/pull/252

So it seems like this is doing what is intended -- catching non-bit-for-bit changes when Rayleigh friction is on.  I can turn it off and make sure the QU240 and QUwISC240 tests pass.  But that doesn't explain the baroclinic channel, ice shelf 2D and ISOMIP+ differences, none of which has Rayleigh damping turned on.

**Comment by xylar** [comment]
@mark-petersen, I retested without Rayleigh damping and the QU240 tests are now bit-for-bit.  But many tests still fail the comparison and Rayleigh damping not the cause (as I suspected):
```
Test Runtimes:
00:07 FAIL ocean_baroclinic_channel_10km_threads_test
00:07 FAIL ocean_baroclinic_channel_10km_decomp_test
00:08 FAIL ocean_baroclinic_channel_10km_restart_test
00:51 FAIL ocean_global_ocean_EC30to60_PHC_performance_test
00:58 FAIL ocean_global_ocean_ECwISC30to60_PHC_performance_test
00:17 FAIL ocean_ice_shelf_2d_5km_z-star_restart_test
01:01 FAIL ocean_isomip_plus_2km_z-star_Ocean0
```

**Comment by xylar** [comment]
The `EC*30to60` tests are the most noteworthy, since I would expect that E3SM would be testing with a similar configuration but we may need to diff the namelist options to be sure.

**Comment by mark-petersen** [comment]
Comparing the baroclinic_channel with QU240, the QU240 has these flags that might be related to vertical mixing that differ:
```
config_use_cvmix_convection = .true.
config_use_cvmix_shear = .true.
config_cvmix_shear_mixing_scheme = 'KPP'
config_use_cvmix_kpp = .true.

  &forcing
      config_use_variable_drag = .true.
      config_use_bulk_wind_stress = .true.
      config_use_bulk_thickness_flux = .true.

  &vegetation_drag
      config_use_vegetation_drag = .true.
      config_use_vegetation_manning_equation = .true.
```
The forcing and vegetation drag are extras that are turned on in the QU240. I bet it is the cvmix set. Specifically, there are blocks of code in `mpas_ocn_vmix.F` with 
```
if ( config_cvmix_kpp_nonlocal_with_implicit_mix ) then
...
else
...
```
so it uses a different code block depending on these two flags
```
Passes BFB before/after:
config_cvmix_shear_mixing_scheme = 'KPP'
config_use_cvmix_kpp = .true.

Fails BFB before/after:
config_cvmix_shear_mixing_scheme = 'PP'
config_use_cvmix_kpp = .false.
```
This matches the E3SM setting, which passes:
```
components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml:212:
<config_cvmix_shear_mixing_scheme>'KPP'</config_cvmix_shear_mixing_scheme>

components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml:221:
<config_use_cvmix_kpp>.true.</config_use_cvmix_kpp>

```
@xylar, could you rerun your test with those two? Thanks. If that still fails the match, then all four cvmix flags at the top?

As a side note, Luke explained to me once why there is both a `config_cvmix_shear_mixing_scheme = 'KPP'` and a logical `config_use_cvmix_kpp = .true.`, but I forgot the explanation. That was intentional, but it is definitely confusing.

**Comment by xylar** [comment]
Thanks @mark-petersen, I'll try that tomorrow.

**Comment by xylar** [comment]
For the time being, we are allowing the non-bit-for-bit changes from https://github.com/E3SM-Project/E3SM/pull/4680.  Once these can be addressed (e.g. with fewer special cases in the vmix code), we will revisit these changes.

**Comment by xylar** [comment]
@mark-petersen, would you be willing to test that compass results are bit-for-bit between:
https://github.com/E3SM-Project/E3SM/commit/c764017ca6ac6c2f877e2a48c9bace1248896698
(the commit that brought in https://github.com/E3SM-Project/E3SM/pull/4680) and this version of the E3SM-Project submodule?  I will do the same using the `pr` test suite with Intel and Intel-MPI on Anvil.  I think that should be sufficient to let this go in.

**Comment by xylar** [comment]
Hmm, obviously the `QU240` test cases are non-bit-for-bit with the baseline because of the coriolis fix in https://github.com/E3SM-Project/E3SM/pull/4750.  I think I'm okay with letting those fail the comparison since we know the old results are garbage.

**Comment by xylar** [comment]
## Testing

On anvil, I'm seeing the following with the `pr` test suite using Intel and Intel-MPI, and using E3SM commit https://github.com/E3SM-Project/E3SM/commit/c764017ca6ac6c2f877e2a48c9bace1248896698 as a baseline:
```
Test Runtimes:
00:09 PASS ocean_baroclinic_channel_10km_default
00:15 PASS ocean_baroclinic_channel_10km_threads_test
00:14 PASS ocean_baroclinic_channel_10km_decomp_test
00:16 PASS ocean_baroclinic_channel_10km_restart_test
03:22 PASS ocean_global_convergence_cosine_bell
00:38 PASS ocean_global_ocean_QU240_mesh
00:30 PASS ocean_global_ocean_QU240_PHC_init
00:25 FAIL ocean_global_ocean_QU240_PHC_performance_test
00:50 FAIL ocean_global_ocean_QU240_PHC_restart_test
00:48 FAIL ocean_global_ocean_QU240_PHC_decomp_test
00:49 FAIL ocean_global_ocean_QU240_PHC_threads_test
00:35 FAIL ocean_global_ocean_QU240_PHC_analysis_test
00:54 FAIL ocean_global_ocean_QU240_PHC_dynamic_adjustment
01:16 PASS ocean_global_ocean_QU240_PHC_files_for_e3sm
00:29 FAIL ocean_global_ocean_QU240_PHC_RK4_performance_test
00:51 FAIL ocean_global_ocean_QU240_PHC_RK4_restart_test
00:48 FAIL ocean_global_ocean_QU240_PHC_RK4_decomp_test
00:49 FAIL ocean_global_ocean_QU240_PHC_RK4_threads_test
00:00 PASS ocean_global_ocean_QUwISC240_mesh
00:01 PASS ocean_global_ocean_QUwISC240_PHC_init
00:26 PASS ocean_global_ocean_QUwISC240_PHC_performance_test
00:00 PASS ocean_global_ocean_EC30to60_mesh
00:02 PASS ocean_global_ocean_EC30to60_PHC_init
01:14 PASS ocean_global_ocean_EC30to60_PHC_performance_test
00:00 PASS ocean_global_ocean_ECwISC30to60_mesh
00:03 PASS ocean_global_ocean_ECwISC30to60_PHC_init
01:20 PASS ocean_global_ocean_ECwISC30to60_PHC_performance_test
00:33 PASS ocean_ice_shelf_2d_5km_z-star_restart_test
00:33 PASS ocean_ice_shelf_2d_5km_z-level_restart_test
01:36 PASS ocean_isomip_plus_2km_z-star_Ocean0
00:20 PASS ocean_ziso_20km_default
00:12 PASS ocean_ziso_20km_with_frazil
Total runtime 20:25
FAIL: 10 tests failed, see above.
```
These 10 failures are expected because of the mistake in the coriolis parameter that was fixed in https://github.com/E3SM-Project/E3SM/pull/4750

**Review by mark-petersen — APPROVED** [review]
I tested on grizzly with gnu (debug and optimized) and see the identical behavior. I agree that we understand the diffs, and it is best to update the submodule now.

**Comment by xylar** [comment]
thanks, @mark-petersen!

**Pull request merged**
