### PR TITLE
Add monthly output test and update daily output test to match

### PR DESCRIPTION
**Pull request by xylar**
This merge adds a test for `timeSeriesStatsMonthly` on the QU240 mesh.  It also updates the stream for the equivalent `timeSeriesStatsDaily` stream to match.

A shorter time step (30 minutes) is needed for the QU240 run to make it through a one-month simulation.

This merge requires https://github.com/E3SM-Project/E3SM/pull/5026

### CODE REVIEW

**Comment by xylar** [comment]
@darincomeau, in the daily output, I copied and pasted the `timeSeriesStatsMonthlyOutput` stream from:
```
...E3SM/darincomeau/ocn/update-output-variables/components/mpas-ocean/default_inputs/streams.ocean.forward
```
after building the model.  The fields are not in the order you specified them in the registry because MPAS seems to put them in the order `var_struct`, then `var_array`, then `var`.

**Comment by xylar** [comment]
## Testing

I ran both tests on my laptop using @darincomeau's branch that updates `timeSeriesStatsMonthly`:
```
compass setup -n 98c 99c 105 106 -p ~/code/e3sm/E3SM/darincomeau/ocn/update-output-variables/components/mpas-ocean/ -w ~/data/mpas/test_20220617/qu240_daily_monthly -f ../compass/inej.cfg
```
I used cached versions of the mesh and init steps (98 and 99) to save a little time.

Both tests ran successfully and I verified that a handful of the new variables (e.g. `zMid` and `atmosphericPressure`) are in the output.

**Comment by xylar** [comment]
@darincomeau, could you give this a try (e.g. on Anvil)?

Clone compass, add my remote, make a worktree for this branch, and hard reset:
```
module load git
mkdir compass
git clone git@github.com:MPAS-Dev/compass.git master
cd master
git remote add xylar/compass git@github.com:xylar/compass.git
git fetch --all -p
git worktree add ../test_time_series_stats_monthly
cd ../test_time_series_stats_monthly
git reset --hard xylar/compass/test_time_series_stats_monthly
```
Now make a new environment for this testing (and install Miniconda3 if you don't already have it), using the default compiler and MPI (Intel and Intel-MPI):
```
./conda/configure_compass_env.py --conda ~/miniconda3 --env_name compass_daily_monthly
```
Assuming that works, source the load script:
```
source load_compass_daily_monthly_anvil_intel_impi.sh
```
Now build standalone MPAS-Ocean in your E3SM branch, e.g.
```
cd ~/e3sm_work/E3SM/darincomeau/ocn/update-output-variables
git submodule update --init --recursive
cd components/mpas-ocean
make intel-mpi
```
Now, you can set up the compass tests:
```
compass setup -n 98c 99c 105 106 -p . -w /lcrc/group/e3sm/ac.dcomeau/...
```
My work directory would be `/lcrc/group/e3sm/ac.xylar/compass_1.1/anvil/test_20220617/qu240_daily_monthly` but I'm sure you have (or want to establish) your own conventions.

Finally, submit the job:
```
cd /lcrc/group/e3sm/ac.dcomeau/...
sbatch compass_job_script.sh
```
You can also run on an interactive node, of course.

**Comment by darincomeau** [comment]
Thanks for the detailed instructions @xylar - worked flawlessly!

```
Test Runtimes:
00:00 PASS ocean_global_ocean_QU240_mesh
00:00 PASS ocean_global_ocean_QU240_PHC_init
00:46 PASS ocean_global_ocean_QU240_PHC_daily_output_test
05:12 PASS ocean_global_ocean_QU240_PHC_monthly_output_test
Total runtime 06:01
PASS: All passed successfully!
```

**Review by darincomeau — APPROVED** [review]
Approve based on above testing.

**Pull request merged**
