### PR TITLE
Add support for perlmutter CPU nodes

### PR DESCRIPTION
**Pull request by xylar**
This requires updating to mache 1.8.0 and bumping compass to 1.2.0-alpha.2.

Albany is not yet working, see: https://github.com/E3SM-Project/spack/issues/6

### CODE REVIEW

**Comment by xylar** [comment]
I was able to get a compass environment set up, I built MPASO, I set up the `pr` test suite, and I submitted a job on Perlmutter CPU.  I didn't get it to run, though, because the compute nodes are down.

Trying Albany next.

**Comment by xylar** [comment]
## Testing

# I ran the ocean PR test suite on Perlmutter!!!

Much better luck than on Chicoma.  It seems that the only hiccup is that we shouldn't try to take advantage of hyperthreading (at least not for now).  My tests with 2 MPI tasks per core mostly hung, though one crashed and one went through.  Without hyperthreading (1 MPI task per core), I haven't seen any trouble.

I did also see some file system issues on interactive nodes (stale file handles).  Hopefully, these are just temporary hiccups as Perlmutter goes into production.

**Comment by xylar** [comment]
@mark-petersen, could you also make sure you can run the PR test suite on Perlmutter?

**Comment by mark-petersen** [comment]
Great work! I'm not able to reproduce it yet. I've tried both gnu and intel. From the head of this PR, after ssh to `perlmutter-p1.nersc.gov`:

<details>
<summary> with gnu </summary> <p>

```
./conda/configure_compass_env.py --conda ~/miconda3 --compiler gnu
Logging to: conda/logs/prebootstrap.log

Doing initial setup

Updating conda environment for installing compass

Creating the compass conda environment


 Running:
   source /global/homes/m/mpeterse/miconda3/etc/profile.d/conda.sh
   conda activate compass_bootstrap
   /global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py --conda /global/homes/m/mpeterse/miconda3 --compiler gnu

Logging to: conda/logs/bootstrap.log

Configuring environment(s) for the following compilers and MPI libraries:
  gnu, mpich

creating dev_compass_1.2.0-alpha.2_mpich
Traceback (most recent call last):
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py", line 917, in <module>
    main()
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py", line 845, in main
    build_conda_env(
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py", line 286, in build_conda_env
    check_call(commands, logger=logger)
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/shared.py", line 144, in check_call
    raise subprocess.CalledProcessError(process.returncode, commands)
subprocess.CalledProcessError: Command 'source /global/homes/m/mpeterse/miconda3/etc/profile.d/conda.sh; conda activate; mamba create -y -n dev_compass_1.2.0-alpha.2_mpich --override-channels -c conda-forge -c defaults -c e3sm/label/compass --file spec-file-mpich.txt python=3.9' returned non-zero exit status 1.
Traceback (most recent call last):
  File "./conda/configure_compass_env.py", line 118, in <module>
    main()
  File "./conda/configure_compass_env.py", line 114, in main
    bootstrap(activate_install_env, source_path, local_conda_build)
  File "./conda/configure_compass_env.py", line 46, in bootstrap
    check_call(command)
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/shared.py", line 144, in check_call
    raise subprocess.CalledProcessError(process.returncode, commands)
subprocess.CalledProcessError: Command 'source /global/homes/m/mpeterse/miconda3/etc/profile.d/conda.sh; conda activate compass_bootstrap; /global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py --conda /global/homes/m/mpeterse/miconda3 --compiler gnu' returned non-zero exit status 1
```
</details>

<details>
<summary> with intel: </summary> <p>

```
./conda/configure_compass_env.py --conda ~/miconda3 --compiler intel
Logging to: conda/logs/prebootstrap.log

Doing initial setup

Updating conda environment for installing compass

Creating the compass conda environment


 Running:
   source /global/homes/m/mpeterse/miconda3/etc/profile.d/conda.sh
   conda activate compass_bootstrap
   /global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py --conda /global/homes/m/mpeterse/miconda3 --compiler intel

Logging to: conda/logs/bootstrap.log

Traceback (most recent call last):
  File "/global/homes/m/mpeterse/miconda3/envs/compass_bootstrap/lib/python3.10/configparser.py", line 790, in get
    value = d[option]
  File "/global/homes/m/mpeterse/miconda3/envs/compass_bootstrap/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/global/homes/m/mpeterse/miconda3/envs/compass_bootstrap/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'mpi_intel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py", line 917, in <module>
    main()
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py", line 790, in main
    compilers, mpis = get_compilers_mpis(config, machine, args.compilers,
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py", line 131, in get_compilers_mpis
    mpi = config.get('deploy', 'mpi_{}'.format(compiler))
  File "/global/homes/m/mpeterse/miconda3/envs/compass_bootstrap/lib/python3.10/configparser.py", line 793, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'mpi_intel' in section: 'deploy'
Traceback (most recent call last):
  File "./conda/configure_compass_env.py", line 118, in <module>
    main()
  File "./conda/configure_compass_env.py", line 114, in main
    bootstrap(activate_install_env, source_path, local_conda_build)
  File "./conda/configure_compass_env.py", line 46, in bootstrap
    check_call(command)
  File "/global/u2/m/mpeterse/repos/compass/pr/conda/shared.py", line 144, in check_call
    raise subprocess.CalledProcessError(process.returncode, commands)
subprocess.CalledProcessError: Command 'source /global/homes/m/mpeterse/miconda3/etc/profile.d/conda.sh; conda activate compass_bootstrap; /global/u2/m/mpeterse/repos/compass/pr/conda/bootstrap.py --conda /global/homes/m/mpeterse/miconda3 --compiler intel' returned non-zero exit status 1
```
</details>

@xylar you said 'the important thing is that mache gets update to 1.7.0.' Does that happen automatically on the head of this PR because of commit b853a436?

**Comment by xylar** [comment]
@mark-petersen, thanks for trying this.  Sorry it didn't work yet.

Can you try the following?
```
./conda/configure_compass_env.py --conda ~/miconda3 --recreate
```
This should make sure you get the new mache.  If that doesn't work, can you post the contents of `conda/logs/*.log`?

`gnu` is the only compiler supported on Perlmutter for now (`intel` is not available and I don't think will be -- the other compilers are for GPUs).

**Comment by xylar** [comment]
> you said 'the important thing is that mache gets update to 1.7.0.' Does that happen automatically on the head of this PR because of commit https://github.com/MPAS-Dev/compass/commit/b853a4368787c76bf1d8df8a73b9d3d6083c38f4?

Not unless you include `--recreate`.  That's because you need the right mache in both the compass environment and in the environment used to install compass.

**Comment by xylar** [comment]
> Do we need to switch from gnu-nersc to gfortran? 

No, I definitely used `gnu-nersc` and I think that should be required.  I didn't try `gfortran` but that isn't the right thing to use on any cray machine.  (We should rename `*-nersc` to `*-cray`.)  I don't think it should be working for you although it may be that Spack makes its own wrappers that might trick that into working, but possibly for the wrong reasons.

> There does not appear to be a scratch space yet.

Yes, there is.  `$SCRATCH` worked fine for me.  It's in `/pscratch`.

> To summarize, @xylar, what was your make command (both gnu and intel?), what was your salloc command, and did you use a scratch space on perlmutter? Thanks!

Again, there is no intel, just gnu.  I just used `make gnu-nersc` and that worked fine for me.  

My `salloc` was:
```
salloc --nodes 1 --qos interactive --time 1:00:00 --constraint cpu -A e3sm
```

I just used `$SCRATCH`:
```
compass suite -s -c ocean -t pr -p E3SM-Project/components/mpas-ocean/ -w $SCRATCH/compass_1.2/test_20221028/ocean_pr
```

**Comment by xylar** [comment]
> OK, if I remove my old `~/miconda3` directory and then `./conda/configure_compass_env.py --conda ~/miconda3 --recreate`

Okay, that's not a problem but it was overkill.  `--recreate` on its own would have recreated the install environment (`temp_compas_install`) without having to completely reinstall Miniconda from scratch.

**Comment by mark-petersen** [comment]
Thanks @xylar that is very helpful. For whatever reason, I kept getting errors with `./conda/configure_compass_env.py --conda ~/miconda3 --recreate` until I just removed  `~/miconda3`. 

I still get `Failed to compile a PIO test program` with both:
```
make gnu-nersc CORE=ocean USE_PIO2=true OPENMP=false DEBUG=true
make gnu-nersc CORE=ocean USE_PIO2=false OPENMP=false DEBUG=true
```
What does your `module list` show before compile? Maybe I have something loaded by mistake.

**Comment by xylar** [comment]
```
> module list

Currently Loaded Modules:
  1) craype-x86-milan
  2) libfabric/1.15.0.0
  3) craype-network-ofi
  4) xpmem/2.4.4-2.3_13.8__gff0e1d9.shasta
  5) xalt/2.10.2
  6) gpu/1.0
  7) cray-dsmml/0.2.2
  8) PrgEnv-gnu/8.3.3
  9) gcc/11.2.0
 10) craype-accel-host
 11) cray-libsci/21.08.1.2
 12) craype/2.7.16
 13) cray-mpich/8.1.15
 14) cray-hdf5-parallel/1.12.1.1
 15) cray-netcdf-hdf5parallel/4.8.1.1
 16) cray-parallel-netcdf/1.12.2.1
 17) cmake/3.22.0
```

**Comment by xylar** [comment]
@mark-petersen, can you comment out the redirect to `/dev/null` in the Makefile to find out what the compiler error actually is?  It usually has nothing to do with PIO.

**Comment by xylar** [comment]
Note that the load script sets:
```
export USE_PIO2=true
export OPENMP=true
```
so you don't need to do those.

**Comment by xylar** [comment]
@mark-petersen, could you either post or point me to your load script (and make sure I have permission to cat it)?  Could you also check of your `.bashrc`, `.bash_profile`, `.bash_profile.ext`, etc. have anything in them that might be causing weird modules to load?

Could you verify that Perlmutter should be getting recognized by doing `echo $NERSC_HOST`?

**Comment by mark-petersen** [comment]
I think that last one is the problem. I have:
```
echo $NERSC_HOST
unknown
```
which is set here:
```
 cat .bashrc.ext
...
if [ -e /usr/common/usg/bin/nersc_host ]; then
  export NERSC_HOST=`/usr/common/usg/bin/nersc_host`
else
  export NERSC_HOST="unknown"
fi
```
When I comment those lines out, [as recommended here](https://docs.nersc.gov/environment/), a new login gives
```
echo $NERSC_HOST
perlmutter
```
I'm recreating my conda compass environment now. As a side note, [the nersc page](https://docs.nersc.gov/environment/) recommends getting rid of the old `*.ext` files completely.

**Comment by xylar** [comment]
Yes, I'm not sure why you didn't trigger this error in `mache`:
https://github.com/E3SM-Project/mache/blob/1.7.0/mache/discover.py#L48-L55

**Comment by xylar** [comment]
Yes, we need to spread the word that folks need to delete their `*.ext` files on NERSC.

**Comment by mark-petersen** [comment]
The error message was triggered correctly. That NERSC_HOST variable had old settings in both my `.bash_profile.ext` and `.bashrc.ext`, and I removed the wrong one the first time.

**Review by mark-petersen — APPROVED** [review]
This all works great! I was able to compile stand-alone MPAS-Ocean and test the nightly suite with gnu, both debug and optimized. To summarize, these were my commands:
```
# in the compass directory for this PR:
./conda/configure_compass_env.py --conda ~/miconda3 --recreate
source load_dev_compass_1.2.0-alpha.2_pm-cpu_gnu_mpich.sh
cd /global/homes/m/mpeterse/repos/E3SM/master/components/mpas-ocean
make clean
make gnu-nersc
compass suite -s -c ocean -t nightly \
   -p /global/homes/m/mpeterse/repos/E3SM/master/components/mpas-ocean \
   -w /pscratch/sd/m/mpeterse/runs/n/$DIR
salloc --nodes 4 --qos interactive --time 1:00:00 --constraint cpu -A e3sm
source load_dev_compass_1.2.0-alpha.2_pm-cpu_gnu_mpich.sh # (specify full path)
cd /pscratch/sd/m/mpeterse/runs/n/$DIR
compass run
```
If you have trouble with these commands, make sure that
```
echo $NERSC_HOST
perlmutter
```

**Comment by xylar** [comment]
@mark-petersen, thanks so much for testing!  Before I merge this, I will need to build shared spack environments on all the systems.  I'd like to release `mache` 1.8.0 before I do that to save myself a little work.  Just so you know why I'm holding off a little on merging.

**Comment by xylar** [comment]
Thanks again, @mark-petersen!

**Pull request merged**
