### PR TITLE
Add the `gotm` test group and `default` test case

### PR DESCRIPTION
**Pull request by xylar**
These are ported from the `ocean/gotm/2.5km/default` test case in legacy COMPASS.

This merge also adds documentation of the new test group.

### CODE REVIEW

**Comment by xylar** [comment]
This test group is used as the example in the tutorial in #128.

**Comment by xylar** [comment]
## Testing

Using my Ubuntu laptop and Gnu, I ran the legacy test case and this test case, comparing the results of ``init`` and ``analysis``.  (I didn't have an efficient way of comparing the results of ``forward`` but could do so if desired.)  The analysis plots looked identical.

**Comment by xylar** [comment]
@qingli411, it would be helpful to have this merged soon-ish so it is available to new developers as an example.  But I also recognize that you have not used the new `compass` yet and you may need to read the documentation and get up to speed before you're ready to review this.  Please let me know if you're able to review and, if so, on what time scale.  Thanks very much in advance!

**Comment by qingli411** [comment]
@xylar, thanks for this and the tutorial in https://github.com/MPAS-Dev/compass/pull/128! I'm certainly interested in learning the new compass and testing this. But I'm currently traveling out of town and won't be able to test it until 6/11 when I come back. Does that work?

**Comment by xylar** [comment]
@qingli411, for this PR, I'm more than happy to wait.  For #128, we may go ahead just so it's in for new developers to work from.  But your feedback after-the-fact would be very much appreciated.  It's easy to put in another PR later with updates and fixes.

**Comment by qingli411** [comment]
@xylar, this sounds good. Please go ahead with https://github.com/MPAS-Dev/compass/pull/128. I will test this PR when I get back and let you know.

**Comment by xylar** [comment]
This needs to be rebased after #138 goes in.

**Review by qingli411 — APPROVED** [review]
@xylar This looks good to me. I also tested the gotm case in this PR on Cori with GNU and it works great.

**Comment by xylar** [comment]
@qingli411, thanks so much for reviewing.

**Pull request merged**
