### PR TITLE
Add ocean wetting-and-drying ramp tests

### PR DESCRIPTION
**Pull request by cbegeman**
This PR is for testing the wetting-and-drying ramp feature introduced in https://github.com/E3SM-Project/E3SM/pull/5590

Checklist
* [X] User's Guide has been updated
* [X] Developer's Guide has been updated
* [X] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [X] The `E3SM-Project` submodule has been updated with relevant E3SM changes
* [X] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes
* [X] New tests have been added to a test suite

### CODE REVIEW

**Review by sbrus89 — APPROVED** [review]
The ramped dam break and drying slope cases run successfully with debug flags on compy with small O(1e-5) - O(1e-2) max differences to the default ssh solution.

**Comment by cbegeman** [comment]
@sbrus89 Thank you for reviewing!

**Comment by cbegeman** [comment]
### Testing

PR suite comparison between this branch (with E3SM submodule update to include ramp feature) and main on chrys with intel, openmpi compiler: PASS

wetdry_ramp suite on chrys with intel, openmpi compiler: PASS

**Comment by cbegeman** [comment]
@xylar Can you take a look at this before I merge since I'm updating the E3SM submodule?

**Comment by xylar** [comment]
Thanks @cbegeman.  I'll post something by tomorrow morning about any testing I do for the update of the E3SM submodule, and we will hopefully be good to go.

**Comment by xylar** [comment]
This merge updates the E3SM-Project submodule from [de075c7](https://github.com/E3SM-Project/E3SM/tree/de075c7) to [c9a0d20](https://github.com/E3SM-Project/E3SM/tree/c9a0d20).

This update includes the following MPAS-Ocean and MPAS-Frameworks PRs (check mark indicates bit-for-bit with previous PR in the list):
- [x]  (ocn) https://github.com/E3SM-Project/E3SM/pull/5618
- [x]  (ocn) https://github.com/E3SM-Project/E3SM/pull/5475
- [x]  (ocn) https://github.com/E3SM-Project/E3SM/pull/5590

**Comment by xylar** [comment]
@cbegeman, this is ready to merge as far as I'm concerned.

**Review by xylar — APPROVED** [review]

**Comment by cbegeman** [comment]
@xylar Thank you for doing that testing!

**Pull request merged**
