### PR TITLE
Add wetdry suite

### PR DESCRIPTION
**Pull request by sbrus89**
This adds a suite containing all wetting and drying test cases.

### CODE REVIEW

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
@sbrus89, if you have tested this, please post something about it.

**Review by cbegeman — APPROVED** [review]
Approved based on testing with Chrys, intel-mpi, E3SM/master @ 28dd4d7bee. Thanks @sbrus89!

**Comment by xylar** [comment]
@cbegeman, presumably we can eventually add an ISOMIP+ test case or 2.

**Comment by xylar** [comment]
Thanks @sbrus89 for adding this!

**Pull request merged**
