### PR TITLE
Update E3SM-Project submodule

### PR DESCRIPTION
**Pull request by xylar**
This merge updates the `E3SM-Project` submodule to the merge of https://github.com/E3SM-Project/E3SM/pull/4457.  This merge leads to non-bit-for-bit changes in:
```
ocean/global_ocean/QU240/PHC/dynamic_adjustment
ocean/global_ocean/ECwISC30to60/PHC/performance_test
ocean/ice_shelf_2d/5km/z-level/restart_test
```

In all three tests, the differences are small enough that we are approving these changes as the new baseline.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the `pr` suite on the update `E3SM-Project`, using the previous commit from that submodule as a baseline.  Three test cases failed due to non-bit-for-bit changes as indicated above.  Below are the differences for each test case.

`ocean/global_ocean/QU240/PHC/dynamic_adjustment`:

```
normalVelocity       Time index: 0
0:  l1: 1.59225521656481e-08  l2: 1.49303787111421e-08  linf: 1.49011611938477e-08
```

`ocean/global_ocean/ECwISC30to60/PHC/performance_test`:

```
normalVelocity       Time index: 0, 1, 2, 3
3:  l1: 4.54747350886464e-13  l2: 4.54747350886464e-13  linf: 4.54747350886464e-13

ssh                  Time index: 0, 1, 2
1:  l1: 2.51709764143015e-12  l2: 4.33391026133586e-13  linf: 2.02504679691629e-13
2:  l1: 1.95257143786876e-11  l2: 1.56628747075416e-12  linf: 8.84625706021325e-13

landIceFrictionVelocity Time index: 0, 1, 2
1:  l1: 4.49488536669040e-14  l2: 7.61067622108892e-15  linf: 3.21097315403307e-15
2:  l1: 2.74167407526837e-13  l2: 1.41597253013961e-14  linf: 2.89351875792931e-15

landIceBoundaryLayerTemperature Time index: 0, 1, 2
1:  l1: 1.83053572300196e-12  l2: 1.64996623183678e-13  linf: 7.01660951563099e-14
2:  l1: 2.01916398098051e-11  l2: 1.92140396421154e-12  linf: 1.53299595240242e-12

landIceBoundaryLayerSalinity Time index: 0, 1, 2
1:  l1: 4.05009359383257e-12  l2: 2.01724071282831e-13  linf: 2.84217094304040e-14
2:  l1: 2.42934561356378e-11  l2: 5.48224127526292e-13  linf: 1.70530256582424e-13

landIceHeatTransferVelocity Time index: 0, 1, 2
1:  l1: 4.94507999002428e-16  l2: 8.37168866859196e-17  linf: 3.53178857687153e-17
2:  l1: 3.01595567638903e-15  l2: 1.55756868950152e-16  linf: 3.18281100260276e-17

landIceSaltTransferVelocity Time index: 0, 1, 2
1:  l1: 1.39349625317541e-17  l2: 2.35933657996309e-18  linf: 9.95475471260616e-19
2:  l1: 8.49995444987322e-17  l2: 4.38948404393659e-18  linf: 8.97007891142304e-19
```

`ocean/ice_shelf_2d/5km/z-level/restart_test`:

```
landIceFrictionVelocity Time index: 0
0:  l1: 3.46944695195361e-17  l2: 6.43252680903426e-18  linf: 1.73472347597681e-18

topDrag              Time index: 0
0:  l1: 4.00107605903053e-16  l2: 4.01516156020076e-17  linf: 7.25412102284367e-18

topDragMagnitude     Time index: 0
0:  l1: 2.08337148782167e-16  l2: 3.21973662823425e-17  linf: 9.05866809387109e-18

landIceFreshwaterFlux Time index: 0
0:  l1: 6.19311459754135e-13  l2: 7.82529105137336e-14  linf: 1.58980901360239e-14

landIceHeatFlux      Time index: 0
0:  l1: 2.10391135624377e-07  l2: 2.66023866381175e-08  linf: 5.40444489161018e-09

heatFluxToLandIce    Time index: 0
0:  l1: 1.87357684922063e-09  l2: 2.46966970853426e-10  linf: 4.99653651786502e-11

landIceBoundaryLayerTemperature Time index: 0
0:  l1: 4.75698946900138e-08  l2: 5.13901494602567e-09  linf: 8.75918115816887e-10

landIceBoundaryLayerSalinity Time index: 0
0:  l1: 7.87942155966448e-09  l2: 8.46113153339408e-10  linf: 1.34548372443533e-10

landIceHeatTransferVelocity Time index: 0
0:  l1: 3.72694496791892e-19  l2: 7.34529468386530e-20  linf: 2.03287907341032e-20

landIceSaltTransferVelocity Time index: 0
0:  l1: 1.16467030247466e-20  l2: 2.09094505157200e-21  linf: 5.29395592033938e-22

landIceInterfaceTemperature Time index: 0
0:  l1: 3.07687209044616e-10  l2: 3.80901246139830e-11  linf: 7.71516184272514e-12

landIceInterfaceSalinity Time index: 0
0:  l1: 5.21806597930663e-09  l2: 6.43898300537612e-10  linf: 1.30327748593118e-10

accumulatedLandIceMass Time index: 0
0:  l1: 1.85796378282532e-10  l2: 2.34763584137109e-11  linf: 4.76951811378967e-12

accumulatedLandIceHeat Time index: 0
0:  l1: 5.62066588827292e-07  l2: 7.40891254290248e-08  linf: 1.49893821799196e-08

ssh                  Time index: 0
0:  l1: 3.19744231092045e-13  l2: 6.05005338838055e-14  linf: 1.77635683940025e-14
```

**Comment by xylar** [comment]
@cbegeman, could you take a look at the differences listed above for the `ocean/ice_shelf_2d/5km/z-level/restart_test` test case and let me know if they are concerning to you?  You may want to look at the changes in https://github.com/E3SM-Project/E3SM/pull/4457 and see if any might have handled inactive top cells incorrectly.

**Comment by xylar** [comment]
@mark-petersen and @philipwjones, could you also take a look at the diffs above and see if you think they are acceptable?  It seems like  https://github.com/E3SM-Project/E3SM/pull/4457 was designed to be bit-for-bit in E3SM but that's not what I'm seeing for several quantities.

I did careful testing of the `ocean/ice_shelf_2d/5km/z-level/restart_test` test case and the changes in that test case are definitely introduced by https://github.com/E3SM-Project/E3SM/pull/4457.  I can't say with 100% certainty that the other changes were introduced by that PR; https://github.com/E3SM-Project/E3SM/pull/4452 would also be a candidate for those 2 and I can investigate further if the changes seem large or would not have been expected in https://github.com/E3SM-Project/E3SM/pull/4457.

**Review by mark-petersen — APPROVED** [review]
Yes, please update E3SM-Project submodule. Note that these two tests,
```
ocean/global_ocean/QU240/PHC/dynamic_adjustment
ocean/global_ocean/ECwISC30to60/PHC/performance_test
```
compare bfb against the previous E3SM-Project with gnu, so this does not appear to be a bug or even an explicit change in order of operations. It may be a compiler-dependant change in order of operations under the hood, but differences in most variables are machine precision.

**Review by cbegeman — APPROVED** [review]
I took a look at those two PRs and everything visually looks ok to me. I think it's reasonably likely that it's a compiler-dependent thing as Mark said, since there are places where, e.g., `kmin` is used instead of `minLevelCell` in some loops in the advection schemes. We saw that when we put in the `minLevelCell` changes so I'm fine proceeding with these small diffs. Thanks for looking into this, @xylar

**Comment by xylar** [comment]
Great, thanks you both, @mark-petersen and @cbegeman.  I'm going to proceed.  @philipwjones, if you have additional feedback, let us know.

**Comment by mark-petersen** [comment]
Pertaining to https://github.com/MPAS-Dev/compass/issues/235, I reran the tests between the previous and updated E3SM-Project in this PR but with double precision output, and bfb testing produced non-bfb for the same tests.

**Pull request merged**
