### PR TITLE
Bugfix for dam break tests

### PR DESCRIPTION
**Pull request by cbegeman**
In order to avoid crashes of the dam break test case, tracers need to be initialized  (currently handled in init mode and fixed here https://github.com/E3SM-Ocean-Discussion/E3SM/pull/33), and those tracers also need to be stored in the initial state stream (fixed here). 

Related changes also included here are (1) adding the validation step to the test case and (2) disabling tracer tendencies, which are not needed in this test case.

### CODE REVIEW

**Comment by cbegeman** [comment]
Note: The results of this test case are not BFB with master prior to https://github.com/E3SM-Project/E3SM/pull/5154, but the general behavior with respect the the SSH field is unchanged.

**Review by sbrus89 — APPROVED** [review]
Approved based on testing this on Compy in conjunction with https://github.com/E3SM-Project/E3SM/pull/5279. Thanks @cbegeman. Sorry again for the delay on this.

**Review by xylar — APPROVED** [review]
This looks great to me! I tested along with https://github.com/E3SM-Project/E3SM/pull/5279 on Chrysalis with Intel and Intel-MPI.  I tested both 40 and 120 cm cases.

I tested the validation as well (by rerunning the test and comparing with the previous run) and that also worked as expected.

**Comment by xylar** [comment]
I will merge this as soon as https://github.com/E3SM-Project/E3SM/pull/5279 has been merged and we update the `E3SM-Project` submodule to include that update.

**Comment by xylar** [comment]
Thanks @cbegeman!!!

**Pull request merged**
