### PR TITLE
Update E3SM-Project to latest master

### PR DESCRIPTION
**Pull request by xylar**
commit hash: 5fa795e1adbf94795445b81bdb290bee8a18ba57

Among other things, this update is intended to bring in the [addition of MARBL](https://github.com/E3SM-Project/E3SM/pull/4587) so that code can be used in compass.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

Chrysalis
- [ ] `pr` with `intel` and `intel-mpi`
- [ ] `pr` with `gnu` and `openmpi`
- [ ] `nightly` with `intel` and `intel-mpi` in debug mode
- [ ] `nightly` with `gnu` and `openmpi` in debug mode

**Comment by xylar** [comment]
@mark-petersen, you can let me know if you want to do any testing yourself.  Otherwise, we can just update.

@ytakano3, all I would want from you is for you to verify that the new `E3SM-Project` submodule has what you need to run with MARBL. In compass in the directory where you cloned the repo, do:
```
git fetch --all -p
git worktree add ../update_e3sm_project
cd ../update_e3sm_project
git reset --hard xylar/compass/update_e3sm_project
git submodule update --init --recursive
cd E3SM-Project
```
Make sure you see what you need.  Build the model if necessary.

**Comment by ytakano3** [comment]
@xylar I managed check and see the modules for MARBL. I need to talk to @maltrud to further check we have modules, codes we need so will follow up again soon.

**Review by mark-petersen — APPROVED** [review]
I used the head of this PR for the command
```
./conda/configure_compass_env.py --conda ~/miconda3 --compiler gnu
./conda/configure_compass_env.py --conda ~/miconda3 --compiler intel
```
on grizzly. Updated to the submodule here, and ran the `pr` test suite for both gnu and intel. Everything works perfectly.

**Comment by xylar** [comment]
@ytakano3, I'm going to take your earlier message as an approval.  This is the latest `master` so it should have any changes you need unless they simply aren't part of E3SM yet.

**Comment by xylar** [comment]
@mark-petersen, thanks very much for testing!

**Pull request merged**
