### PR TITLE
Update E3SM-Project submodule

### LINKED ISSUE #308: SST in WC14 stand-alone spin-up warms to 60C
An unphysical warming to 60C on the Indonesian coast occurs in the WC14 stand-alone spin-up using compass/master 2270c038, even after fixing the Coriolis bug noted in #304. This can be seen with:
```
compass/ocean/tests/global_ocean/init/namelist.init
-config_expand_sphere = .false.
+config_expand_sphere = .true.

compass list|grep WC14
  95: ocean/global_ocean/WC14/mesh
  96: ocean/global_ocean/WC14/PHC/init
  97: ocean/global_ocean/WC14/PHC/performance_test
  98: ocean/global_ocean/WC14/PHC/dynamic_adjustment

compass setup -f Config_dir/e3sm_master -w $DIR -n 95 96 97 98
```
After running these steps on grizzly with `load_dev_compass_1.0.0_grizzly_gnu_mvapich.sh`, the error can be seen here:
```
cd /lustre/scratch4/turquoise/mpeterse/runs/220126_compass_master_E3SM_head_gr_gfortran_openmp_WC1402
cd ocean/global_ocean/WC14/PHC/dynamic_adjustment/simulation/analysis_members/

ncdump -v temperatureMax globalStats.*.nc |tail -n 2
    60.5092380065623, 60.5138480143581, 60.5184557681456, 60.5230611583427 ;
```
It reaches 60C by day 25 of the simulation.

### PR DESCRIPTION
**Pull request by xylar**
This merge updates the E3SM-Project submodule to match today's [E3SM/master](https://github.com/E3SM-Project/E3SM/tree/7b87d1faa545f7da4e792058401ad3bc04434c85)
Commit hash: 7b87d1faa545f7da4e792058401ad3bc04434c85

Merges of interest to compass:
* [Add mostRecentAccessTime attribute to streams](https://github.com/E3SM-Project/E3SM/pull/4752) - MALI
* [GPU port of thickness tendency with OpenACC](https://github.com/E3SM-Project/E3SM/pull/4792) - MPAS-Ocean
* [Extending OpenACC diagnostics up to time integration](https://github.com/E3SM-Project/E3SM/pull/4813) - MPAS-Ocean
* [Fix non-standard declarations of 8-byte integers in ESMF in MPAS-Framework](https://github.com/E3SM-Project/E3SM/pull/4825) - MPAS Framework
* [Add -fallow-argument-mismatch to gfortran in MPAS standalone builds](https://github.com/E3SM-Project/E3SM/pull/4821) - MPAS Framework
* [Turn off Redi diagonal terms for shallow columns](https://github.com/E3SM-Project/E3SM/pull/4785) - MPAS-Ocean

closes #308

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the `pr` test suite on Anvil with Intel and Intel-MPI (optimized).  I used `master` with the previous E3SM-Project submodule as a baseline.

As expected, I'm seeing non-bit-for-bit changes in many `global_ocean` tests (those that use Redi).

Unfortunately, I'm also seeing non-bit-for-bit in a lot of other tests that shouldn't have been.  All tests run successfully but the comparison fails for many:
```
00:08 PASS ocean_baroclinic_channel_10km_default
00:15 FAIL ocean_baroclinic_channel_10km_threads_test
00:14 FAIL ocean_baroclinic_channel_10km_decomp_test
00:16 FAIL ocean_baroclinic_channel_10km_restart_test
03:15 PASS ocean_global_convergence_cosine_bell
00:39 PASS ocean_global_ocean_QU240_mesh
00:31 PASS ocean_global_ocean_QU240_PHC_init
00:25 FAIL ocean_global_ocean_QU240_PHC_performance_test
00:51 FAIL ocean_global_ocean_QU240_PHC_restart_test
00:49 FAIL ocean_global_ocean_QU240_PHC_decomp_test
00:50 FAIL ocean_global_ocean_QU240_PHC_threads_test
00:36 FAIL ocean_global_ocean_QU240_PHC_analysis_test
00:55 FAIL ocean_global_ocean_QU240_PHC_dynamic_adjustment
01:46 PASS ocean_global_ocean_QU240_PHC_files_for_e3sm
00:29 FAIL ocean_global_ocean_QU240_PHC_RK4_performance_test
00:52 FAIL ocean_global_ocean_QU240_PHC_RK4_restart_test
00:48 FAIL ocean_global_ocean_QU240_PHC_RK4_decomp_test
00:50 FAIL ocean_global_ocean_QU240_PHC_RK4_threads_test
00:00 PASS ocean_global_ocean_QUwISC240_mesh
00:00 PASS ocean_global_ocean_QUwISC240_PHC_init
00:26 FAIL ocean_global_ocean_QUwISC240_PHC_performance_test
00:00 PASS ocean_global_ocean_EC30to60_mesh
00:02 PASS ocean_global_ocean_EC30to60_PHC_init
01:10 FAIL ocean_global_ocean_EC30to60_PHC_performance_test
00:00 PASS ocean_global_ocean_ECwISC30to60_mesh
00:02 PASS ocean_global_ocean_ECwISC30to60_PHC_init
01:12 FAIL ocean_global_ocean_ECwISC30to60_PHC_performance_test
00:33 FAIL ocean_ice_shelf_2d_5km_z-star_restart_test
00:34 PASS ocean_ice_shelf_2d_5km_z-level_restart_test
01:36 FAIL ocean_isomip_plus_2km_z-star_Ocean0
00:12 PASS ocean_ziso_20km_default
00:11 FAIL ocean_ziso_20km_with_frazil
```

**Comment by xylar** [comment]
@sbrus89, I may need to bust out `git bisect` to track these down.  Or I it might even be time to write `compass bisect`...

**Review by mark-petersen — APPROVED** [review]
I tested the nightly suite on grizzly with both gnu and intel 19. I compared the commit just before the Redi column one  (https://github.com/E3SM-Project/E3SM/commit/11f02f2aa7) against the previous baseline on this PR (https://github.com/E3SM-Project/E3SM/commit/44814ae) and the PASSED the comparison on all tests. So it looks like @xylar's intel test failure was due to something in his set-up.

Then I compared the head (https://github.com/E3SM-Project/E3SM/commit/7b87d1fa) to just before the Redi column one (https://github.com/E3SM-Project/E3SM/commit/11f02f2aa7) and the tests with Redi did not match, as expected: 
```
00:10 PASS ocean_baroclinic_channel_10km_default
00:16 PASS ocean_baroclinic_channel_10km_threads_test
00:15 PASS ocean_baroclinic_channel_10km_decomp_test
00:17 PASS ocean_baroclinic_channel_10km_restart_test
00:41 PASS ocean_global_ocean_QU240_mesh
00:31 PASS ocean_global_ocean_QU240_PHC_init
00:31 FAIL ocean_global_ocean_QU240_PHC_performance_test
01:04 FAIL ocean_global_ocean_QU240_PHC_restart_test
01:02 FAIL ocean_global_ocean_QU240_PHC_decomp_test
01:03 FAIL ocean_global_ocean_QU240_PHC_threads_test
00:48 FAIL ocean_global_ocean_QU240_PHC_analysis_test
00:30 FAIL ocean_global_ocean_QU240_PHC_RK4_performance_test
01:04 FAIL ocean_global_ocean_QU240_PHC_RK4_restart_test
01:02 FAIL ocean_global_ocean_QU240_PHC_RK4_decomp_test
01:02 FAIL ocean_global_ocean_QU240_PHC_RK4_threads_test
00:00 PASS ocean_global_ocean_QUwISC240_mesh
00:00 PASS ocean_global_ocean_QUwISC240_PHC_init
00:33 FAIL ocean_global_ocean_QUwISC240_PHC_performance_test
00:33 PASS ocean_ice_shelf_2d_5km_z-star_restart_test
00:34 PASS ocean_ice_shelf_2d_5km_z-level_restart_test
00:15 PASS ocean_ziso_20km_default
00:13 PASS ocean_ziso_20km_with_frazil
```
but everything passed the execution.

**Comment by xylar** [comment]
On Chrysalis with Intel and Intel-MPI, comparing the updated E3SM-Project submodule with the current submodule as a baseline, I'm seeing:
```
00:04 PASS ocean_baroclinic_channel_10km_default
00:07 PASS ocean_baroclinic_channel_10km_threads_test
00:07 PASS ocean_baroclinic_channel_10km_decomp_test
00:08 PASS ocean_baroclinic_channel_10km_restart_test
02:02 PASS ocean_global_convergence_cosine_bell
00:33 PASS ocean_global_ocean_QU240_mesh
00:24 PASS ocean_global_ocean_QU240_PHC_init
00:22 FAIL ocean_global_ocean_QU240_PHC_performance_test
00:44 FAIL ocean_global_ocean_QU240_PHC_restart_test
00:43 FAIL ocean_global_ocean_QU240_PHC_decomp_test
00:43 FAIL ocean_global_ocean_QU240_PHC_threads_test
00:29 FAIL ocean_global_ocean_QU240_PHC_analysis_test
00:47 FAIL ocean_global_ocean_QU240_PHC_dynamic_adjustment
01:02 PASS ocean_global_ocean_QU240_PHC_files_for_e3sm
00:23 FAIL ocean_global_ocean_QU240_PHC_RK4_performance_test
00:43 FAIL ocean_global_ocean_QU240_PHC_RK4_restart_test
00:42 FAIL ocean_global_ocean_QU240_PHC_RK4_decomp_test
00:42 FAIL ocean_global_ocean_QU240_PHC_RK4_threads_test
00:00 PASS ocean_global_ocean_QUwISC240_mesh
00:00 PASS ocean_global_ocean_QUwISC240_PHC_init
00:22 FAIL ocean_global_ocean_QUwISC240_PHC_performance_test
00:00 PASS ocean_global_ocean_EC30to60_mesh
00:01 PASS ocean_global_ocean_EC30to60_PHC_init
00:52 FAIL ocean_global_ocean_EC30to60_PHC_performance_test
00:00 PASS ocean_global_ocean_ECwISC30to60_mesh
00:02 PASS ocean_global_ocean_ECwISC30to60_PHC_init
00:57 FAIL ocean_global_ocean_ECwISC30to60_PHC_performance_test
00:17 PASS ocean_ice_shelf_2d_5km_z-star_restart_test
00:17 PASS ocean_ice_shelf_2d_5km_z-level_restart_test
01:01 PASS ocean_isomip_plus_2km_z-star_Ocean0
00:08 PASS ocean_ziso_20km_default
00:06 PASS ocean_ziso_20km_with_frazil
```
So the expected results.  I will test the same with OpenMPI (with both Intel and Gnu) but everything looks good.  It seems like Intel and Intel-MPI on Anvil is just producing non-bit-for-bit results, whereas everywhere else is happy.  I think we can let it be.

**Comment by xylar** [comment]
@mark-petersen, thanks very much for testing and approving!

**Comment by xylar** [comment]
Everything looks good on Chrysalis (with Intel and Intel-MPI; Intel and OpenMPI; and Gnu and OpenMPI).  Merging...

**Pull request merged**
