### PR TITLE
Add histograms of areaCell and dcEdge to init plots

### PR DESCRIPTION
**Pull request by xylar**
Last 2 plots in:
initial_state

Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the IcoswISC30 mesh and init tests on Chrysalis to produce the image above.

**Comment by xylar** [comment]
@golaz and @proteanplanet, are you okay with these or are there more tweaks you'd like to see?

**Comment by xylar** [comment]
The frequency is on a log scale for other plots, Perhaps that would make sense here, too.  I'll try that.

**Comment by xylar** [comment]
initial_state

Yeah, probably the version on a log scale makes a bit more sense for consistency and because there's a bit more info there.

**Comment by xylar** [comment]
I fixed the min/max values to be the original ones (m^2 and m, rather than km^2 and km) to hopefully avoid potential confusion.

**Review by proteanplanet — APPROVED** [review]
Approved by visual inspection.  Thanks for adding this as a QC metric.

**Comment by xylar** [comment]
Thanks @proteanplanet!

**Pull request merged**
