### PR TITLE
Update E3SM-Project to E3SM/master

### PR DESCRIPTION
**Pull request by xylar**
commit hash: d57fb310cbdcb10197a7aa29767976e3955f4475

This update includes the following MPAS-Ocean PRs:
* https://github.com/E3SM-Project/E3SM/pull/4832
* https://github.com/E3SM-Project/E3SM/pull/4835
* https://github.com/E3SM-Project/E3SM/pull/4866
* https://github.com/E3SM-Project/E3SM/pull/4868
* https://github.com/E3SM-Project/E3SM/pull/4472
* https://github.com/E3SM-Project/E3SM/pull/4910

And the following MPAS framework PRS:
* https://github.com/E3SM-Project/E3SM/pull/4854
* https://github.com/E3SM-Project/E3SM/pull/4910

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I am doing tests on the new E3SM-Project submodule with the old one as a baseline on Anvil.  Here are the ocean `pr` test suites I've run (checked means they completed):
- [x] intel impi - 21 tests are non-bit-for-bit
- [x] intel impi debug
- [x] intel openmpi
- [x] intel openmpi debug
- [x] intel mvapich - 3 tests fail execution (a known issue #336)
- [ ] intel mvapich debug
- [x] gnu openmpi
- [x] gnu openmpi debug
- [x] gnu mvapich
- [x] gnu mvapich debug

**Comment by xylar** [comment]
I investigated the non-bit-for-bit changes on Anvil with Intel and Intel-MPI.  They are small (machine precision) and can be traced to https://github.com/E3SM-Project/E3SM/pull/4472 (using #354).  I recommend we don't try to do anything about them.  This particular combination has been a problem before for us (e.g. https://github.com/MPAS-Dev/compass/pull/326#issuecomment-1072866367).

**Comment by xylar** [comment]
@sbrus89, I'm flagging you to review because this brings in https://github.com/E3SM-Project/E3SM/pull/4472 and just wanted to see if you want to double check that it's actually there as expected.

@mark-petersen, could you maybe run some tests on a machine other than Anvil?  You could test out the matrix build utility if you want.  Or just build by hand as usual.

**Review by mark-petersen — APPROVED** [review]
Tested with gnu on grizzly with the nightly suite, and I get bfb on all tests between the two submodule hashes. Thanks!

**Comment by xylar** [comment]
Thanks @mark-petersen.

**Comment by xylar** [comment]
@sbrus89, I'm taking you off as a reviewer because I think this has been tested plenty.  But this should mean #348 is closer to ready.

**Pull request merged**
