### PR TITLE
Add bathymetry remapping

### PR DESCRIPTION
**Pull request by xylar**
This merge adds a step for remapping bathymetry and ice-shelf topography to the ocean framework.  It also adds this step to the mesh test cases in `global_ocean`.  It updates the `cull_mesh` step to use the remapped bathymetry to determine the land mask if topography remapping was performed.  It updates most meshes to use the this new approach, leaving the QU240 and Icos240 meshes as they were for more efficient testing.  Finally, this merge modifies the topography output with the variable names expected in MPAS-Ocean init mode and creates a stream for reading them in.

An alteration is needed to MPAS-Ocean to bypass reading in the land-ice topography from a lon-lat file.  Such a bypass exists for the bathymetry but not for land-ice topography.

Needs: https://github.com/E3SM-Project/E3SM/pull/5553

Checklist
* [x] User's Guide has been updated
* [x] Developer's Guide has been updated
* [x] API documentation in the Developer's Guide (`api.rst`) has any new or modified class, method and/or functions listed
* [x] Documentation has been [built locally](https://mpas-dev.github.io/compass/latest/developers_guide/building_docs.html) and changes look as expected
* [x] The `E3SM-Project` submodule has been updated with relevant E3SM changes - merged in #585 
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the `ECwISC30to60`, `SOwISC12to60` and `WCwISC14` meshes through `mesh`, `init` and `performance_test` test cases with this branch:
```
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/test_20230402/remap_bathy
```
All 3 completed successfully.

The initial condition are in:
```
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/test_20230402/remap_bathy/ecwisc/ocean/global_ocean/ECwISC30to60/PHC/init/initial_state/
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/test_20230402/remap_bathy/sowisc/ocean/global_ocean/SOwISC12to60/PHC/init/initial_state/
/lcrc/group/e3sm/ac.xylar/compass_1.2/chrysalis/test_20230402/remap_bathy/wcwisc/ocean/global_ocean/WCwISC14/PHC/init/initial_state/
```
Here are 2 screenshots of the bathymetry (`bottomDepth`) from the SORRM mesh, first in the high-res region:
weddell

Then, in the low res region:
north_atlantic

**Comment by xylar** [comment]
@milenaveneziani, is this something you are willing to review?  Who else would you suggest I ask?

**Comment by milenaveneziani** [comment]
Thanks @xylar. What do you think would be the best way to review this?

**Comment by xylar** [comment]
@milenaveneziani, that's a good question.  I wasn't thinking of a code review, just looking at the initial condition.  Maybe the place to start is to look at `bottomDepth` in ParaView as I did, though I realize this isn't very quantitative.  I think we're only going to notice dynamical problems when we run simulations so I guess what I was hoping for is that you might check for weird issues like you had spotted in the Chukchi Sea in the previous bathymetry.

**Comment by milenaveneziani** [comment]
Sounds good. I'll do that.

**Comment by milenaveneziani** [comment]
@xylar: I looked at the 3 bathymetry fields in paraview, paying particular attention to the SO shelves, Arctic and Canadian Archipelago, Florida St and Indonesia Throughflow region. I do not see anything strange.
I even learned about the Aleutian Trench: I was wondering why the bathymetry would become suddenly so deep just south of the Aleutian Islands, and indeed there is a trench arch there!

**Review by milenaveneziani — APPROVED** [review]
Approved based on visual inspection of `bottomDepth` for the 3 meshes.

**Comment by xylar** [comment]
Thanks so much, @milenaveneziani!

**Pull request merged**
