### PR TITLE
add the variable 'zbnds' for ocean depth

### PR DESCRIPTION
**Pull request by hollyhan**
This PR adds the renaming of the ismip6 variable `z_bnds` to the MALI variable `ismip6shelfMelt_zBndsOcean`, which was previously dropped in the `ismip6_forcing` test group & `ocean_thermal` test case. The reason for the change is that the bounds of each ocean layer are needed in the ocean re-extrapolation scheme in MALI.

Along with the main change mentioned above, the PR also includes some clean-up to address PEP8-related errors raised by `pre-commit`. 

Checklist
* [x] Document (in a comment titled `Testing` in this PR) any testing that was used to verify the changes

### CODE REVIEW

**Comment by hollyhan** [comment]
Testing: 
1. Processing thermal forcing file from ocean model (e.g., UKESM SSP585, which has `time` as a dimension in `z_bnds`)
```
(compass_test) pn2034311:1995-2300 hollyhan$ ncdump -v ismip6shelfMelt_zBndsOcean AIS_8to30km_TF_UKESM1-0-LL_SSP585_2300.nc 
netcdf AIS_8to30km_TF_UKESM1-0-LL_SSP585_2300 {
dimensions:
	Time = UNLIMITED ; // (306 currently)
	nCells = 98341 ;
	nISMIP6OceanLayers = 30 ;
	TWO = 2 ;
	StrLen = 64 ;
variables:
	double ismip6shelfMelt_zBndsOcean(nISMIP6OceanLayers, TWO) ;
 ismip6shelfMelt_zBndsOcean =
  -0, -60,
  -60, -120,
  -120, -180,
  -180, -240,
  -240, -300,
  -300, -360,
  -360, -420,
  -420, -480,
  -480, -540,
  -540, -600,
  -600, -660,
  -660, -720,
  -720, -780,
  -780, -840,
  -840, -900,
  -900, -960,
  -960, -1020,
  -1020, -1080,
  -1080, -1140,
  -1140, -1200,
  -1200, -1260,
  -1260, -1320,
  -1320, -1380,
  -1380, -1440,
  -1440, -1500,
  -1500, -1560,
  -1560, -1620,
  -1620, -1680,
  -1680, -1740,
  -1740, -1800 ;
}
```
3. Processing observation file (

**Comment by xylar** [comment]
@hollyhan, this looks great to me!  I'm just waiting on your MALI testing and then I'll be happy to merge this.

**Comment by xylar** [comment]
@hollyhan, could you post some test results from using this in MALI?  It doesn't need to be much, just an indication that you could successfully read the file written out by this branch into MALI.

**Comment by hollyhan** [comment]
@xylar, sorry this was left behind for such a long time. I can successfully read the file from this branch using MALI; below are the print statements I wrote out in the MALI output file. 

```
 =============================
 Starting timestep number 1
 =============================

 CFL dt adjusted for fractions (days): advective=296.334828746526, diffusive=1157407.40740741, calving=92592592592.5926, face-melting=115740740740.741
 Timestep limited by advective CFL condition.
   Setting time step (days) to: 296.334826388889
   Completed timestep.  New time is: 2015-10-24_08:02:09
 ocean data will be extrapolated into the MALI ice draft
 printing iLayer: 1
 printing layertop depth -0.00000000000000 meters
 printing iLayer: 2
 printing layertop depth -60.0000000000000 meters
 printing iLayer: 3
 printing layertop depth -120.000000000000 meters
 printing iLayer: 4
 printing layertop depth -180.000000000000 meters
 printing iLayer: 5
 printing layertop depth -240.000000000000 meters
 printing iLayer: 6
 printing layertop depth -300.000000000000 meters
 printing iLayer: 7
 printing layertop depth -360.000000000000 meters
 printing iLayer: 8 
 printing layertop depth -420.000000000000 meters
 printing iLayer: 9
 printing layertop depth -480.000000000000 meters
 printing iLayer: 10
 printing layertop depth -540.000000000000 meters
 printing iLayer: 11
 printing layertop depth -600.000000000000 meters
 printing iLayer: 12
 printing layertop depth -660.000000000000 meters
 printing iLayer: 13
 printing layertop depth -720.000000000000 meters
 printing iLayer: 14
 printing layertop depth -780.000000000000 meters
 printing iLayer: 15
 printing layertop depth -840.000000000000 meters
 printing iLayer: 16
 printing layertop depth -900.000000000000 meters
 printing iLayer: 17
 printing layertop depth -960.000000000000 meters
 printing iLayer: 18
 printing layertop depth -1020.00000000000 meters
 printing iLayer: 19
 printing layertop depth -1080.00000000000 meters
 printing iLayer: 20
 printing layertop depth -1140.00000000000 meters
 printing iLayer: 21
 printing layertop depth -1200.00000000000 meters
 printing iLayer: 22
 printing layertop depth -1260.00000000000 meters
 printing iLayer: 23
 printing layertop depth -1320.00000000000 meters
 printing iLayer: 24
 printing layertop depth -1380.00000000000 meters
 printing iLayer: 25
 printing layertop depth -1440.00000000000 meters
 printing iLayer: 26
 printing layertop depth -1500.00000000000 meters
 printing iLayer: 27
 printing layertop depth -1560.00000000000 meters
 printing iLayer: 28
 printing layertop depth -1620.00000000000 meters
 printing iLayer: 29
 printing layertop depth -1680.00000000000 meters
 printing iLayer: 30
 printing layertop depth -1740.00000000000 meters
```

**Review by xylar — APPROVED** [review]
@hollyhan, thanks for the test output!

**Pull request merged**
